### PR TITLE
Remove symlinks from repository

### PR DESCRIPTION
**Pull request by mloskot**
# Issue

Implements symlinks removal as discussed in #1976.

## Tasklist

 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Ensure all CI passed

## Requirements / Relations

- @kevinkreiser's https://github.com/valhalla/valhalla/issues/1976#issuecomment-543778517

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@mloskot what about the links in the proto dir to the thirdparty osm lib?

**Comment by mloskot** [comment]
@kevinkreiser  Looks like I wasn't clear about the status of the whole proposal and I took your "for the osm proto definitions we will need (...)" in https://github.com/valhalla/valhalla/issue/1976#issuecomment-543778517 as "we will need to think about it", hence undecided.
So, I submitted this PR only for the part that you clearly confirmed as "can be deteled".

I can issue another OR for the `proto/*` stuff with necessary changes in `CMakeLists.txt`-s. Shall I?

**Comment by kevinkreiser** [comment]
im open to either! if you'd like to do it in another PR that is fine if you'd liek to add it to this PR that is cool as well. as always we appreciate your contributions in any form!

**Comment by mloskot** [comment]
@kevinkreiser I've update this PR with symlinks removal in `proto/`.

Tomorrow I will take care of the remaining symlinks in 

```
./docs/changelog.md -> ../CHANGELOG.md
./docs/index.md -> ../README.md
./run_route_scripts/requests -> ../test_requests
```

Please, don't merge it yet.

**Comment by mloskot** [comment]
@kevinkreiser This PR is ready to review and merge.

The only issue that may need to be clarified is mentioned in this commit https://github.com/valhalla/valhalla/pull/2001/commits/bb11dc6d92da294b51ce85b06c6928b51b6c8563

All files in `mkdocs.yml` are listed with paths relative to `/docs/` directory and not relative to /mkdocs.yml` file, while

**Comment by kevinkreiser** [comment]
@mloskot no worries if we break the readthedocs stuff we'll fix it in another pr

**Pull request merged**
