### PR TITLE
Fix PencilPointUturn threshold to use km rather than meters

### PR DESCRIPTION
**Pull request by danpaz**
# Issue

Noticed difference in units when switching to the length_km naming and comment said meters.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by danpaz** [comment]
# RAD results

## de_benchmark_routes.txt

no diffs

## 1k routes

no diffs

## pencil_point_uturn_routes.txt

2 total diffs.

### 2.txt

`-j '{"locations":[{"lat":38.736004,"lon":-77.275780,"name":"Silverbrook Road"},{"lat":38.736103,"lon":-77.275597,"name":"Silverbrook Road"}],"costing":"auto","directions_options":{"units":"miles"}}'`

image

```
4c4
< [NARRATIVE]    VERBAL_PRE: Drive east on Silverbrook Road, State Route 6 hundred. Then Make a left U-turn to stay on Silverbrook Road.
---
> [NARRATIVE]    VERBAL_PRE: Drive east on Silverbrook Road, State Route 6 hundred. Then Make a sharp left to stay on Silverbrook Road.
7,9c7,9
< [NARRATIVE] 1: Make a left U-turn to stay on Silverbrook Road/SR 600. | 0.1 km
< [NARRATIVE]    VERBAL_ALERT: Make a left U-turn to stay on Silverbrook Road.
< [NARRATIVE]    VERBAL_PRE: Make a left U-turn to stay on Silverbrook Road, State Route 6 hundred. Then You will arrive at your destination.
---
> [NARRATIVE] 1: Make a sharp left to stay on Silverbrook Road/SR 600. | 0.1 km
> [NARRATIVE]    VERBAL_ALERT: Make a sharp left to stay on Silverbrook Road.
> [NARRATIVE]    VERBAL_PRE: Make a sharp left to stay on Silverbrook Road, State Route 6 hundred. Then You will arrive at your destination.
```

### 7.txt

`-j '{"locations":[{"lat":38.869987,"lon":-77.447304,"street":"Stonecroft Boulevard"},{"lat":38.870159,"lon":-77.447243,"street":"Stonecroft Boulevard"}],"costing":"auto","directions_options":{"units":"miles"}}'`

image


```
4c4
< [NARRATIVE]    VERBAL_PRE: Drive southeast on Stonecroft Boulevard. Then Make a left U-turn to stay on Stonecroft Boulevard.
---
> [NARRATIVE]    VERBAL_PRE: Drive southeast on Stonecroft Boulevard. Then Make a sharp left to stay on Stonecroft Boulevard.
7,9c7,9
< [NARRATIVE] 1: Make a left U-turn to stay on Stonecroft Boulevard. | 0.1 km
< [NARRATIVE]    VERBAL_ALERT: Make a left U-turn to stay on Stonecroft Boulevard.
< [NARRATIVE]    VERBAL_PRE: Make a left U-turn to stay on Stonecroft Boulevard. Then, in 100 meters, You will arrive at your destination.
---
> [NARRATIVE] 1: Make a sharp left to stay on Stonecroft Boulevard. | 0.1 km
> [NARRATIVE]    VERBAL_ALERT: Make a sharp left to stay on Stonecroft Boulevard.
> [NARRATIVE]    VERBAL_PRE: Make a sharp left to stay on Stonecroft Boulevard. Then, in 100 meters, You will arrive at your destination.
```

@dgearhart I was a little surprised these changed, do these diffs look expected to you?

**Comment by danpaz** [comment]
@dgearhart updated to use the simpler angle check and toss the short-distance check. Added a simple gurka test for good measure as well. FInally ran RAD and found 0 diffs on:

bicycle_routes
pedestrian_routes
internal_edge_routes
1k routes
de_benchmark_routes
pencil_point_uturn_routes

**Review by dgearhart — DISMISSED** [review]
excellent - :ship: :pencil2:

**Review by dgearhart — APPROVED** [review]
:shipit:

**Pull request merged**
