### PR TITLE
Removed voice & banner instructions from last step and added ssmlAnnouncements

### PR DESCRIPTION
**Pull request by Trietes**
# Issue

This PR is targetting to solve two of the issues mentioned in #4640. I've added simple voice ssmlAnnouncements to make the routing answers compatible with the navigation SDKs. I've also removed the voice and banner instructions from the last step since they are not required by the SDKs and just lead to confusing instructions on the screen.

## Tasklist

 - [X] Add tests
 - [X] Add #fixes with the issue number that this PR addresses
 - [x] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Review by eikes — COMMENTED** [review]
I was not aware that the MapBox navigation SDK requires a `ssmlAnnouncement` but thank you for adding that.

I'll have to check what happens in the MapLibre navigation SDK when the last `bannerInstructions` and `voiceInstructions` are empty, I assume that it still works.

**Comment by Trietes** [comment]
> I was not aware that the MapBox navigation SDK requires a `ssmlAnnouncement` but thank you for adding that.

Might also depend on the SDK version. In my case the app just crashed. I would guess mapbox navigation SDK set this as requiered at some point.

> I'll have to check what happens in the MapLibre navigation SDK when the last `bannerInstructions` and `voiceInstructions` are empty, I assume that it still works.

Would be really cool if you can do this. At least directions API V5 of mapbox always returns empty lists in the last step. So I guess it shouldn't be a probelm for Maplibre. In case of Mapbox Navigation SDK it just leads to the strange side effects mentioned in the Issue.

**Comment by ianthetechie** [comment]
Yeah, I can confirm that some versions of the Mapbox-derived SDKs will crash without this. In our API middle layer for navigation at Stadia Maps, we added SSML `<speak>{}</speak>` wrapping exactly like this PR 😂 

> I'll have to check what happens in the MapLibre navigation SDK when the last bannerInstructions and voiceInstructions are empty, I assume that it still works.

This should work in every SDK I'm aware of (incl. newer ones like Ferrostar).

Anyone able to fix up the conflicts + get this merged? Seems pretty straightforward and low-risk to me :D

**Review by ianthetechie — APPROVED** [review]

**Comment by Trietes** [comment]
Thanks for updating the branch! Should be ready for merging now.

**Comment by eikes** [comment]
I tried the directions from this branch and they work just as well. Thanks! 

I would love to see some further improvements in the voice directions. @Trietes you mentioned that you made them less annoying on short steps. Is that something we could incorporate into the main repository?

**Review by eikes — APPROVED** [review]
I have tried this and it works fine. Adding the `ssmlAnnouncement` is nice improvement.

**Review by kevinkreiser — APPROVED** [review]
thanks all!

**Comment by Trietes** [comment]
@eikes I've opened a draft merge request here: https://github.com/valhalla/valhalla/pull/4696. It already got tested by @ianthetechie and by myself. I'm basically waiting for a maintainer to say he would be willing to merge it and then I would start cleaning it up and adding some tests to get it ready to merge. I would also appreciate it a lot if you would give it a test. Maybe you've also some suggestions how to improve it even more. Or we can add more improvements later on in more MR's

**Comment by eis-ioki** [comment]
@Trietes I will definitely check it out and give it a try!

**Comment by eikes** [comment]
@Trietes I will definitively give it a try!

**Comment by Jab2870** [comment]
> Just wanted to give a small update on this: I've it running now with an Maplibre app. Works fine on my side

@Trietes - My apologies for commenting on a closed PR, but is this Maplibre + valhalla project publicly available anywhere? It's something i'd be very interested in if it were.

**Comment by Trietes** [comment]
> > Just wanted to give a small update on this: I've it running now with an Maplibre app. Works fine on my side
> 
> @Trietes - My apologies for commenting on a closed PR, but is this Maplibre + valhalla navigation project publicly available anywhere? It's something i'd be very interested in if it were.

Unforuntely the project is company property, so I can't make it public :/ But would be super if somebody would publish an example of using Valhalla with Maplibre. I will probably won't have time for doing it

**Comment by ianthetechie** [comment]
@Jab2870 what are you looking for exactly and on which platforms? Here are some things you might look at depending on what you need.

First, a bit selfishly (since I'm the originator of the project :D), you should check out [Ferrostar](https://github.com/stadiamaps/ferrostar). It's still new (read: some sharp edges), but it's a modern take on a cross-platform navigation SDK, and has frontends for SwiftUI, Jetpack Compose, and the web. It can talk natively to Valhalla servers over an HTTP API or you could also do offline routing with [valhalla-mobile](https://github.com/Rallista/valhalla-mobile). What it lacks in bells and whistles, it makes up for (IMO) with support out-of-the-box for complex costing options, easy integration with any server, etc.

If you want something a bit more mature, MapLibre has FOSS forks of the Mapbox Navigation SDK for [iOS](https://github.com/maplibre/maplibre-navigation-ios) and [Android](https://github.com/maplibre/maplibre-navigation-android); still pretty tightly coupled to Mapbox Directions, but there is movement to make these more generic (nobody developing the projects actually uses these with Mapbox, but the SDKs still have all the baggage from past design decisions.

Bad news: you're in for a pretty large chunk of work either way (in different dimensions). Good news: both are open-source, actively developed, and improving month over month. Which is right for you? It depends ™️

**Comment by Jab2870** [comment]
@ianthetechie ferrostar looks very promising. I'm only interested in the web side, not bothered about ios or android. Thanks for pointing me towards it. I'll have a play.

**Pull request merged**
