### PR TITLE
Increased kDefaultServicePenalty.

### PR DESCRIPTION
**Pull request by maksimandrianov**
# Issue

What's wrong?
Was found case in which, at first, driver received a 3 reroutes (as such U-turn and shortcuts) through service roads to back on the original route, before was suggested correct reroute.
For correct routing driver shouldn't receive such reroutes. This issue can be especially acute in USA due to specific road network.
This issue can't be fixed in the OSM data, because US driver rules allow make left turn to service roads in most this place.

Where were you routing from/to?
Long Island, NY, USA.

What did you expect to happen?
The driver should be suggest U-turn on the main road or reroute through higher class roads then service roads

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by maksimandrianov** [comment]
It's fixed these cases, but we need tolerate increased ETA:

| Before | After |
|-|-|
|||


| Before | After |
|-|-|
|||

**Comment by maksimandrianov** [comment]
I can experiment with penalty values, that impact on U-turns, but it's more complex and can touch more cases in RAD testing. What do you think which way is better?

**Comment by maksimandrianov** [comment]
Also it opened a new issue, that @SvetlanaBayarovich already had mentioned "Dead-end roundabout labels are sometimes placed incorrectly" (incorrect marks Use::kCuldesac).

**Comment by maksimandrianov** [comment]
Some questions from the research:
1. **Could we penalize these sort of turns?** (cases № 2 and 4)
Imagine two alternative roads. First road is represented as one osm way with sharp corners, second - straight osm way:
photo_2021-05-24_15-34-08
Currently Valhalla engine prefers going through first road. It does not penalize these sort of turns. 
 
2. **Could we fix these cases automatically by replacing tag value "service" to "trunk_link"?** (cases № 5 and 12)
Sometimes trunk link roads are marked as service roads. For example, https://www.openstreetmap.org/way/568013065 is the service road, https://www.openstreetmap.org/way/716003464 is the trunk link. But as you can see both are trunk link:
Screenshot 2021-05-24 at 15 58 58
Screenshot 2021-05-24 at 15 59 52

**Comment by kevinkreiser** [comment]
@maksimandrianov those ways are correctly tagged as service, a trunk link should be a ramp onto or off of a trunk road these small "internal" edges are correctly marked as service in my opinion. @gknisely what do you reckon?

https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk_link

also please dont use google maps here. osm.org has aerial imagery from various providers. its on by default in edit mode.

**Comment by maksimandrianov** [comment]
> @maksimandrianov those ways are correctly tagged as service, a trunk link should be a ramp onto or off of a trunk road these small "internal" edges are correctly marked as service in my opinion. @gknisely what do you reckon?
> 
> https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrunk_link
> 
> also please dont use google maps here. osm.org has aerial imagery from various providers. its on by default in edit mode.

But also it is not really "service" road, as can you see in aerial imagery this road quite wide and it is used for do u-turns.

**Comment by gknisely** [comment]
@maksimandrianov users mark these roads as service roads all the time; therefore, you can not penalize these like normal service roads (e.g., https://www.openstreetmap.org/way/568013065)  I am assume these are also marked as internal.  Can you test out not penalizing roads that are service and internal?

**Comment by maksimandrianov** [comment]
> @maksimandrianov users mark these roads as service roads all the time; therefore, you can not penalize these like normal service roads (e.g., https://www.openstreetmap.org/way/568013065) I assume these are also marked as internal. Can you test out not penalizing roads that are service and internal?

I have tested out. RAD testing showы better results when the engine is not penalizing roads that are service and internal. Thanks!

**Comment by gknisely** [comment]
@maksimandrianov looks good but can you add a gurka test where an edge is service and internal and one where the edge is service and not internal.

**Comment by maksimandrianov** [comment]
> @maksimandrianov looks good but can you add a gurka test where an edge is service and internal and one where the edge is service and not internal.

Done!

**Review by gknisely — CHANGES_REQUESTED** [review]
@maksimandrianov tests are failing and you are out of date with master

**Comment by maksimandrianov** [comment]
> @maksimandrianov tests are failing and you are out of date with master

Fixed

**Review by gknisely — APPROVED** [review]

**Pull request merged**
