### PR TITLE
Evaluate restrictions with dow only

### PR DESCRIPTION
**Pull request by CuriOusQuOkka**
# Issue

Noticed, that restrictions with dow only, like Monday-Friday were not applied after routing to the edges. They are not applied to the edges when validating the routing path. 

In the example below, if I set conditional restriction `no_entry @ Mo-Fr` for `AB->BC` left turn
the restriction is ignored,  at any time we receive `AB->BC->CF` path from A to F instead of  `AB->BD->DE->EC->CF` for workdays.

          D----B----A
          |    |
          |    |
          E----C----F

## Tasklist

 - [x] Add tests
 - [x] Add gurka tests with day_on/day_off and no hour info [#3029](https://github.com/valhalla/valhalla/pull/3029)
 - [x] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by gknisely** [comment]
@CuriOusQuOkka I think we will be good after we test with https://github.com/valhalla/valhalla/blob/master/test_requests/timed_access_routes.txt and https://github.com/valhalla/valhalla/blob/master/test_requests/timed_conditional_routes.txt  Let me know if there are any diffs.

**Review by gknisely — DISMISSED** [review]

**Comment by CuriOusQuOkka** [comment]
> @CuriOusQuOkka I think we will be good after we test with https://github.com/valhalla/valhalla/blob/master/test_requests/timed_access_routes.txt and https://github.com/valhalla/valhalla/blob/master/test_requests/timed_conditional_routes.txt Let me know if there are any diffs.

the tests passed.

**Comment by genadz** [comment]
what about gurka test ? I expected to see the example you described in the ticket in gurka tests

**Comment by CuriOusQuOkka** [comment]
> what about gurka test ? I expected to see the example you described in the ticket in gurka tests

@gknisely Added.

**Review by gknisely — APPROVED** [review]

**Review by genadz — APPROVED** [review]

**Pull request merged**
