### PR TITLE
Download and use clang-format 7 from Mason if 7 is not found locally

### PR DESCRIPTION
**Pull request by danpat**
# Issue

NOTE: See UPDATE below - version has been bumped to clang-format 7.0

Not everyone has `clang-format` installed, and when they do, their system may not provide `clang-format` 3.8.  We've settled on 3.8 because it's the lowest-common-demoninator available on some relatively old platforms, and it covers all the formatting rules we currently want.  Changes in formatting behaviour between `clang-format` versions means that it's highly desirable to have everyone formatting code using the same version of `clang-format`.

This PR updates `./scripts/format.sh` to download `clang-format` 3.8 from [mason](https://github.com/mapbox/mason) when version 3.8 isn't found locally.  This should work for both Linux and macOS, and requires no extra steps from developers.

Where users want to use IDE plugins to keep their code formatted while editing, they can run this script once, then point their IDE to `${workspace}/mason_packages/.link/bin/clang-format`, and you'll get to use `clang-format` 3.8, just like we do on our CI system.

## UPDATE:

I've added a commit that bumps the `clang-format` version up to 7.0.  I broke this into a separate commit because we may or may not want to do this.  There are some unavoidable formatting changes between clang-format 3.8 and 7.0 that I could not reconcile by tweaking the `.clang-format` file.  If we're going to update to 7.0, now is the time to do it (following right on the heels of the reformat commit in `master` before anything else gets added).

## Tasklist

 - [ ] review - you must request approval to merge any PR to master

### CODE REVIEW

**Comment by kevinkreiser** [comment]
I think along with this we might want to update the `contributing` section of the `README` to give instructions for how one should use these tools. I was also wondering what our windows contributors (@mloskot and @mtehver) would have to do to be able to continue contributing other than a torturous guessing and watching of the results of CI.

**Comment by mloskot** [comment]
Current VS2017 and VS2017 Preview (this one has built-in clang-format support) come with clang-format 5.0.0

```
C:\> "c:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\Common7\IDE\VC\vcpackages\clang-format.exe" --version
clang-format version 5.0.0 (tags/RELEASE_500/final)

C:\> "c:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\vcpackages\clang-format.exe" --version
clang-format version 5.0.0 (tags/RELEASE_500/final)
```

However, there are official Windows binaries available http://releases.llvm.org/3.8.0/LLVM-3.8.0-win64.exe

```
c:\> "c:\Program Files\LLVM-3.8.0\bin\clang-format.exe" --version
clang-format version 3.8.0 (branches/release_38)
```

Alternatively, there is Ubuntu in WSL available which also can be used to get clang-format.

So, I think this PR does not impose any hurdles for Windows contributors.

**Comment by kevinkreiser** [comment]
@danpat darn so are you confirming that something that isnt 3.8.0 will indeed fail the lint check? or are you saying the linter will be fine but formatting code will make more diffs as we thrash between people who have different versions of the formatter? sorry just trying to be sure im understanding correctly

**Comment by danpat** [comment]
🤔 If there was ever a time to update to clang-format 7, it'd be now - having a major edit like this in the code history is bad enough one time, twice would be 🤕 .  Let me see if I can update this to clang-format 7 and minimize the changes it introduces, maybe it's not too bad if we do it right away.

**Pull request merged**
