### PR TITLE
Enable undefined sanitizer in ci

### PR DESCRIPTION
**Pull request by merkispavel**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@mandeepsandhu the latest changes to skip CI when we update the changelog for example kind of neuter CI..

in this case @merkispavel merges master, builds start, then he changes the changelog which starts another build and cancels the previous builds. the current build says oh yeah just a changelog, no worries everything is ready.

i dont think this is workable. it is really easy, if someone isnt looking closely, to ship stuff that isnt ready to be shipped. not that this is the case but it will screw us down the road

**Comment by kevinkreiser** [comment]
i should mention, the reason why i was diligent and looked at CI was to figure out how long the build took, becuase i knew from experience that enabling this absolutely trashes CI performance:

image

2 hours is not something I can get behind. Lets up the CI machine type and the number of cores it uses and see if we can get the build to something reasonable.

**Comment by merkispavel** [comment]
@kevinkreiser I wonder if 2h CI is caused by completely invalid cache after enabling UBSAN?

**Comment by merkispavel** [comment]
Wow, Though I keep in my skip-ci-on-changelog-update, I have no thoughts about unfinished ci of merge-master pipeline(unintentionally ofc). I'll rebase this branch to trigger "honest" CI run

**Comment by merkispavel** [comment]
> Wow, Though I keep in my skip-ci-on-changelog-update, I had no thoughts about unfinished ci of merge-master pipeline(unintentionally ofc). I'll rebase this branch to trigger "honest" CI run

Damn, `git rebase origin/master` doesn't help: ci is still skipped.. I think we should drop skip-ci step for now and revisit it

**Comment by nilsnolde** [comment]
@kevinkreiser how about this solution (for the time being): https://github.com/valhalla/valhalla/pull/3014#issuecomment-821970848

It doesn't really skip CI on a PR for irrelevant files, but at least it'd skip builds as long as it's a draft PR (or "wip" in title). Though I wonder if #3014 has the same problem (I fear so), I'll give it a try..

**Comment by mandeepsandhu** [comment]
> @mandeepsandhu the latest changes to skip CI when we update the changelog for example kind of neuter CI..
> 
> in this case @merkispavel merges master, builds start, then he changes the changelog which starts another build and cancels the previous builds. the current build says oh yeah just a changelog, no worries everything is ready.
> 
> i dont think this is workable. it is really easy, if someone isnt looking closely, to ship stuff that isnt ready to be shipped. not that this is the case but it will screw us down the road

Yeah, the issue that @merkispavel hit is mentioned here: https://github.com/valhalla/valhalla/blob/master/scripts/needs_ci_run#L36

There's a way to figure out if a prior CI run is in progress or not. If it is, we don't skip CI. If that works, then its safe to push changes even if its a skip-able change, as we don't abort the previous build. For the interim, I'll remove entries from `.ciiignore` so nothing gets skipped. How does that sound @kevinkreiser ?

**Comment by kevinkreiser** [comment]
still taking 2 hours it seems?

**Comment by merkispavel** [comment]
> still taking 2 hours it seems?

yea..

**Comment by merkispavel** [comment]
I expected that the last merge-master commit will take less time because of the hot cache. But I've definitely missing something

**Comment by kevinkreiser** [comment]
@merkispavel i tried this a long time ago and got the same results. our best bet is to change: https://circleci.com/docs/2.0/configuration-reference/#resourceclass

**Comment by merkispavel** [comment]
> @merkispavel i tried this a long time ago and got the same results. our best bet is to change: https://circleci.com/docs/2.0/configuration-reference/#resourceclass

Yeah, I checked that option and circle CI docs about plans and resourceclass
1. What's the circle ci plan do we have? From the docs "MacOS is not yet available on the free plan". And as we have mac os job I guess valhalla is using non-free plan?
2. From the docs "Available resources classes are restricted for customers on the free plan to small/medium for Linux". The default one is "medium"(i believe this is what we use at the moment). If valhalla is on the non-free plan - how much money do we have? 😅 Can we switch build-release resource_class `medium -> large/xlarge`?

**Comment by kevinkreiser** [comment]
@merkispavel yeah im pretty sure you can just pick the larger class. you are correct we are not on the free plan. i would ask @kshehadeh or @rclark to be sure, but i was pretty confident we can use a larger class.

**Comment by mandeepsandhu** [comment]
> @merkispavel yeah im pretty sure you can just pick the larger class. you are correct we are not on the free plan. i would ask @kshehadeh or @rclark to be sure, but i was pretty confident we can use a larger class.

trying out circle's XL instances for speedup: https://github.com/valhalla/valhalla/pull/3043

**Comment by merkispavel** [comment]
@mandeepsandhu this is awesome! Durations looks good. https://app.circleci.com/pipelines/github/valhalla/valhalla/6512/workflows/8355314e-8ffe-4fa0-847a-a3d508f209af
image

**Comment by merkispavel** [comment]
@kevinkreiser the PR looks mergeable after changing resource class https://github.com/valhalla/valhalla/pull/3043. What do you think?

**Review by kevinkreiser — APPROVED** [review]

**Comment by mandeepsandhu** [comment]
Oh man, the duration for `build-release` :disappointed: !  I'm still a bit concerned about the added build time this adds. @merkispavel feel free to bump up paralellism for `build-release` if it helps (we can try 12 or 16 maybe?)

**Comment by kevinkreiser** [comment]
the last build i saw was 23 minutes, that didnt seem so bad compared to the 18 without the sanitizer. or am i missing something. it was probably with cache, but its almost always with cache anyway

**Comment by PureW** [comment]
Almost 1h for a full CI run is a bit painful. Is a full sanitizer run something that we could run nightly against master instead of on every change?

**Comment by PureW** [comment]
> the last build i saw was 23 minutes, that didnt seem so bad compared to the 18 without the sanitizer. or am i missing something. it was probably with cache, but its almost always with cache anyway

Unless I'm missing something, the sanitizer is for the release build, not the debug-lint build?

**Comment by kevinkreiser** [comment]
> EDIT: Oh I see, the subsequent builds were faster.

yeah exactly, it looks like after we upgraded to bigger machines and pavel merged that in it was 23 minutes. that seemed ok to me especially for the extra protection it provides, @mandeepsandhu whats your take?

**Comment by mandeepsandhu** [comment]
> > EDIT: Oh I see, the subsequent builds were faster.
> 
> yeah exactly, it looks like after we upgraded to bigger machines and pavel merged that in it was 23 minutes. that seemed ok to me especially for the extra protection it provides, @mandeepsandhu whats your take?

@kevinkreiser I was looking at this comment from @merkispavel : https://github.com/valhalla/valhalla/pull/2999#issuecomment-829315928 which showed `build-release` took ~48 mins. Did that decrease to 23 after the upgrade to XL instances? (the current CI build is still running so I dont know by how much its improved)

**Comment by mandeepsandhu** [comment]
> > > EDIT: Oh I see, the subsequent builds were faster.
> > 
> > 
> > yeah exactly, it looks like after we upgraded to bigger machines and pavel merged that in it was 23 minutes. that seemed ok to me especially for the extra protection it provides, @mandeepsandhu whats your take?
> 
> @kevinkreiser I was looking at this comment from @merkispavel : [#2999 (comment)](https://github.com/valhalla/valhalla/pull/2999#issuecomment-829315928) which showed `build-release` took ~48 mins. Did that decrease to 23 after the upgrade to XL instances? (the current CI build is still running so I dont know by how much its improved)

BTW I have no objections if its 23 mins or around that duration (48 mins seemed a bit concerning).

**Review by mandeepsandhu — APPROVED** [review]
Ok so both [debug](https://app.circleci.com/pipelines/github/valhalla/valhalla/6529/workflows/485173fc-13ba-4b24-8d9e-5177811415b3/jobs/42430) & [release](https://app.circleci.com/pipelines/github/valhalla/valhalla/6529/workflows/485173fc-13ba-4b24-8d9e-5177811415b3/jobs/42429) builds finished in ~18 mins. Def no objections from my side! :+1: 

Thanks @merkispavel

**Comment by merkispavel** [comment]
I think it's safe to merge it and track `build-release` durations for the next few days/a week. If we notice that caching doesn't work for some reason/works in an unexpected way and build-release takes too long - we can revert it and think about alternatives.
I definitely understand your worries @mandeepsandhu. No rush in pushing additional checking if it slows CI significantly 👍

**Pull request merged**
