### PR TITLE
Allow disabling Werror

### PR DESCRIPTION
**Pull request by PureTryOut**
Mainly useful for distribution packaging where we don't care about
warnings as long as the resulting package works properly. Make sure it
defaults to ON so packaging will have to turn it OFF and warnings
won't accidentally be missed

# Issue

#2923. This doesn't _solve_ it but helps packagers experiencing the same problem.

### CODE REVIEW

**Comment by PureW** [comment]
Looks good to me. I re-triggger the Azure pipeline as the error seemed unrelated to the change.

**Comment by PureTryOut** [comment]
@PureW sorry seems I forgot a spot, I think I caught every place now.

**Comment by mookerji** [comment]
@PureTryOut @PureW we already have this exact cmake flag. see just a few lines up: https://github.com/valhalla/valhalla/blob/d658151cbed872f3606c5c3dfce4583c0c083133/CMakeLists.txt#L33-L37.

We have this default to `OFF` because Valhalla currently has too many warnings to fix ... the build will always fail.

**Comment by PureTryOut** [comment]
Ah yes I missed that. However, it wasn't used everywhere and the build was still failing for me because of it. This PR fixes that, but I will remove that extra line.

**Comment by mookerji** [comment]
@PureTryOut forgot to say: yes, great catch. You're totally right that it wasn't being used for all the targets.

**Comment by PureTryOut** [comment]
@mookerji removed that line, should be good to go now.

**Comment by PureW** [comment]
> @PureTryOut @PureW we already have this exact cmake flag. see just a few lines up:
> 
> https://github.com/valhalla/valhalla/blob/d658151cbed872f3606c5c3dfce4583c0c083133/CMakeLists.txt#L33-L37
> .
> 
> We have this default to `OFF` because Valhalla currently has too many warnings to fix ... the build will always fail.

It's not the exact same thing though. The existing switch enables warnings everywhere which we didn't manage to enable due to existing code.

So we decided to try to migrate piecemeal, file-by-file, to a warning free build. What @PureTryOut is doing is disabling those new warnings/errors on the file-by-file basis.

**Review by PureW — CHANGES_REQUESTED** [review]
The change as is right now disables the file-by-file warnings. See my comment below.

**Comment by PureTryOut** [comment]
Named it `ENABLE_SINGLE_FILES_WERROR` for now, will that do @PureW?

**Review by PureW — APPROVED** [review]
Great, thanks!

**Comment by PureW** [comment]
Looks like Azure is broken again...

**Review by PureW — APPROVED** [review]

**Pull request merged**
