### PR TITLE
Protect against 0 length edge

### PR DESCRIPTION
**Pull request by dnesbitt61**
can happen for origin edges with heading where the only edge selected is an inbound edge to a node snapped location.
@noblige - thanks!

### CODE REVIEW

**Comment by kevinkreiser** [comment]
so the solution here is that we still use the edge with 0 length but we just lie and say its a meter long?

**Comment by dnesbitt61** [comment]
yes - alternatively the search could be modified so that if the location snaps to a node then only outbound edges are run through the heading filter. But that might not handle a through or destination location.

**Comment by kevinkreiser** [comment]
i was wondering if once we have the path we could just chop off that zero length and use the next edge as the first edge with 100% of its length

**Comment by dnesbitt61** [comment]
but then rather than appearing to start the route in the correct heading the route would take whatever heading the second edge has. I'm inclined to go with this for now.

**Comment by kevinkreiser** [comment]
rock and roll

**Pull request merged**
