### PR TITLE
Add graph support for highway=busway

### PR DESCRIPTION
**Pull request by landonreed**
# Issue

This PR targets #2574. While it may not handle all of the cases described in that issue, it aims to expand the routable bus-only ways for bus costing to include the OSM tag `highway=busway`, which according to [OSM docs](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway) should imply `bus=designated`. This is specifically designed to support [some ways in the Brisbane area](https://overpass-turbo.eu/s/1cqh) that are correctly identified as `highway=busway`.

I'm not sure if this warrants a test, but am open to adding one if the maintainers think that would be helpful!

## Tasklist

 - N/A Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - N/A Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [x] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 N/A

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@gknisely maybe this is a good opportunity to throw in a quick gurka test for `bus`?

**Comment by gknisely** [comment]
> @gknisely maybe this is a good opportunity to throw in a quick gurka test for `bus`?

Sure as soon as I get a minute.  Unless @landonreed wants to give it a try

**Comment by landonreed** [comment]
Hey all, I don't have a ton of experience in the valhalla code base, but would be happy to give it a look if that would be helpful!

**Comment by kevinkreiser** [comment]
We dont have any bus specific tests yet but a good place to add some might be in here: https://github.com/valhalla/valhalla/blob/master/test/gurka/test_access_psv.cc where we could confirm `bus` can but `auto` cannot take these ways. Or over in the general routing test: https://github.com/valhalla/valhalla/blob/master/test/gurka/test_route.cc

@landonreed take a look at the general lay out of the gurka tests and give this a read: https://github.com/valhalla/valhalla/tree/master/test/gurka#valhalla-gurka-tests to understand the general philosophy.

**Comment by landonreed** [comment]
@kevinkreiser, thanks for the pointers! Does https://github.com/valhalla/valhalla/pull/3413/commits/a54ac387be25aeda467e0cb2584d5029225b71d5 look to be on the right track? Happy to separate that out into its own `TEST` if that would be better.

**Comment by kevinkreiser** [comment]
@landonreed that test change looks great to me. Now we just have to fix the rest of the build and resolve merge conflicts

**Comment by kevinkreiser** [comment]
@landonreed i modified your testing to make the test cases a bit stronger and also fix the cases you were aiming at. we'll see what the build says but locally everything worked for me after these changes :crossed_fingers:

**Review by kevinkreiser — APPROVED** [review]

**Comment by landonreed** [comment]
That looks great! Thanks for all of the help moving this along, @kevinkreiser!

**Comment by landonreed** [comment]
Hi @kevinkreiser, thanks once again for helping shepherding this along!

I wanted to inquire as to when you expect to cut the next release of valhalla? We have some customers that are interested in some of these changes, but I think we're blocked until the new version with this PR ships.

We're happy to help with anything that might grease the wheels!

**Comment by kevinkreiser** [comment]
@landonreed im not exactly sure what your deployment process is but the only thing our release process does:

1. tagging the repo
2. pushing a tagged docker build to docker hub

You are free to pull and retag our `run-latest` docker image anytime, which has the tip of master in it, if you want to use this for your deployment. In other words nothing about our release cadence should hold you back from deploying this code. Does that make sense?

**Comment by landonreed** [comment]
@kevinkreiser, thanks for the info! That's very helpful. I'll check on how our deployment is handled. We use a third-party hosted service, so there's a little bit of grey area in how they handle releasing new code. An official tagged release might be helpful, but if that's become less common of a practice for the project (or has overhead) maybe we can recommend that they use `run-latest`. 

I'll follow up here if a tagged release seems like our only path forward.

**Comment by kevinkreiser** [comment]
It's just not always a perfect time for a tagged release to be honest. At the moment we have partial support for indoor routing such that you can rout on them but the routes you get don't have maneuvers fleshed out yet. That pr is in progress and once we merge it we can probably tag

**Pull request merged**
