### PR TITLE
Added tags to taginfo.json

### PR DESCRIPTION
**Pull request by acwilton**
Added the bicycle tags that were added with the low-stress biking updates as well as the tags just added for motor scooter costing.

### CODE REVIEW

**Comment by acwilton** [comment]
Wow, didn't realize this was gonna be the 1000th PR. And quite a boring one made by a silly intern too! I guess I should have waited for a cooler PR to come around first for this milestone. ¯\_(ツ)_/¯

**Comment by dnesbitt61** [comment]
I was going to do a one line comment change, so I'm sure yours is more
interesting.

**Comment by gknisely** [comment]
Looks good.  Just make sure it is valid via jsonlint or a json validator.  Also, tests are failing....think you just may need to rerun circle again.  I kicked it off.  We will see.
:+1:

**Comment by dnesbitt61** [comment]
This is valid JSON. Can we merge?

**Comment by gknisely** [comment]
sure i approved after that was confirmed

**Comment by dnesbitt61** [comment]
fixes #901

**Pull request merged**
