### PR TITLE
Finish separating valhalla_build_transit into fetch and convert steps

### PR DESCRIPTION
**Pull request by irees**
# Issue

Hi all. I am doing some maintenance on Transitland, and hope to improve our exported tiles. This PR removes some duplicated transit fetch code and should simplify future maintenance.

Completes the separation of the `valhalla_build_transit` program into two separate programs:
- the existing `valhalla_fetch_transit` (updated to use the `stop_stations` endpoints from `valhalla_build_transit`) 
- a new program, `valhalla_convert_transit` which converts PBF to GPH tiles (essentially `valhalla_build_transit` with fetch-related code removed)

Additionally, a shell script for `valhalla_build_transit` provides backwards compatibility. It runs `valhalla_fetch_transit` immediately followed by `valhalla_convert_transit`. 

A `transitpbf.h` header file contains the transit PBF reading/writing code in common between these programs.

I welcome any suggestions and feedback.

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by gknisely** [comment]
@irees I actually have a PR that I am going to submit soon.  It removes the boost date_time dependency from the transit logic.  Any chance you can grab those updates after I merge?

**Comment by irees** [comment]
@gknisely No problem. I will update the datetime handling after you merge, just tag me or this PR when it's done.

**Comment by irees** [comment]
Thanks @gknisely - I will incorporate your changes to resolve the conflicts soon.

**Comment by gknisely** [comment]
@irees sorry there are so many changes.  If you need help, please let me know.

**Comment by irees** [comment]
@gknisely I was able to merge your changes, it was only minor differences. I am testing now, and will comment again when I am ready for review.

**Comment by gknisely** [comment]
@irees can you try running `./scripts/format.sh` from the valhalla directory.  See if this fixes the failures.

**Comment by irees** [comment]
@gknisely This PR is now up to date with master, and I ran the `format.sh` script. I have also done local testing on fetching/building transit tiles, and everything looks alright. I am ready for review, and any comments/changes you suggest. I'm not sure if the `build-debug` CI test failure is spurious or not, it didn't appear related to anything I'm doing, and it passed in previous builds.

**Comment by irees** [comment]
@gknisely thanks!

**Pull request merged**
