### PR TITLE
Fix all compiler warnings in sif and set to -Werror

### PR DESCRIPTION
**Pull request by danpaz**
# Issue

Just some cleanup in sif to get rid of compiler warnings. Also sets all files in sif to -Werror so we avoid regressing these in the future.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by mandeepsandhu** [comment]
I thought we were removing warnings as we touched files? Is this PR just for removing warnings? If so, why don't we fix all of them in a single PR? It will require thorough testing (although even this PR requires the same level of testing), but will be a one time lift.

**Review by PureW — APPROVED** [review]
:rocket:  This is great!

It seems CI triggered some more errors though with the `-Werror` predicate. (unused variables, you can just delete the variable name and leave the type in the function definition):

```
/root/project/src/sif/autocost.cc:205:52: error: unused parameter 'edge' [-Werror=unused-parameter]
  205 |   virtual Cost EdgeCost(const baldr::DirectedEdge* edge,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/root/project/src/sif/autocost.cc:206:56: error: unused parameter 'departure' [-Werror=unused-parameter]
  206 |                         const baldr::TransitDeparture* departure,
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/root/project/src/sif/autocost.cc:207:40: error: unused parameter 'curr_time' [-Werror=unused-parameter]
  207 |                         const uint32_t curr_time) const override {
      |                         ~~~~~~~~~~~~~~~^~~~~~~~~
/root/project/src/sif/autocost.cc: In member function 'virtual bool valhalla::sif::AutoDataFix::Allowed(const valhalla::baldr::DirectedEdge*, const valhalla::sif::EdgeLabel&, const valhalla::baldr::GraphTile*, const valhalla::baldr::GraphId&, uint64_t, uint32_t, int&) const':
/root/project/src/sif/autocost.cc:1231:41: error: unused parameter 'tile' [-Werror=unused-parameter]
 1231 |                        const GraphTile* tile,
      |                        ~~~~~~~~~~~~~~~~~^~~~
/root/project/src/sif/autocost.cc:1233:39: error: unused parameter 'current_time' [-Werror=unused-parameter]
 1233 |                        const uint64_t current_time,
      |                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~
/root/project/src/sif/autocost.cc:1234:39: error: unused parameter 'tz_index' [-Werror=unused-parameter]
 1234 |                        const uint32_t tz_index,
      |                        ~~~~~~~~~~~~~~~^~~~~~~~
/root/project/src/sif/autocost.cc:1235:29: error: unused parameter 'restriction_idx' [-Werror=unused-parameter]
 1235 |                        int& restriction_idx) const override {
```

**Comment by danpaz** [comment]
> I thought we were removing warnings as we touched files? 

@mandeepsandhu this was simply an opportunistic update, I noticed a spat of compiler warnings when running make that seemed low risk and easy to resolve in a single PR. 

> Is this PR just for removing warnings? If so, why don't we fix all of them in a single PR? 

In previous work (https://github.com/valhalla/valhalla/pull/2035#discussion_r346005516) we found that there are too many thousands of compiler warnings currently to do in a single PR. Biting off piece by piece seems like a more manageable approach to me.

> It will require thorough testing (although even this PR requires the same level of testing), but will be a one time lift.

What kind of testing were you thinking this PR requires? The changes were (1) adding explicit `override` qualifier to methods that were implicitly overriding, (2) deleting the copy constructor for the base class dynamiccost, which should not be used, and (3) deleting unused variables.

**Comment by mandeepsandhu** [comment]
> > Is this PR just for removing warnings? If so, why don't we fix all of them in a single PR?
> 
> In previous work ([#2035 (comment)](https://github.com/valhalla/valhalla/pull/2035#discussion_r346005516)) we found that there are too many thousands of compiler warnings currently to do in a single PR. Biting off piece by piece seems like a more manageable approach to me.
> 

Right, thats why I thought we were going to fix warnings for modules we were changing in PRs that were addressing some current issue (as opposed to pure warning-only fixes). Maybe this is fine since, as you say, this is very restricted set of change.

> > It will require thorough testing (although even this PR requires the same level of testing), but will be a one time lift.
> 
> What kind of testing were you thinking this PR requires? The changes were (1) adding explicit `override` qualifier to methods that were implicitly overriding, (2) deleting the copy constructor for the base class dynamiccost, which should not be used, and (3) deleting unused variables.

I don't know what tests _should_ be run for this particular module. If you're confident that unit & functional tests have good coverage then it should be fine. Not sure if we need to run RAD for such changes.

**Review by mandeepsandhu — APPROVED** [review]

**Comment by danpaz** [comment]
@mandeepsandhu 👍  I'll run a set of RAD tests to be sure.

**Comment by mandeepsandhu** [comment]
> @mandeepsandhu 👍 I'll run a set of RAD tests to be sure.

I think a a few routes for each costing model (pedestrian, cycling, auto etc) should be enough....we don't have to run the big prod 1k/20k routes.

**Comment by danpaz** [comment]
I ran RAD against de_benchmark_routes.txt, demo_routes.txt (including auto and bus costing), pedestrian_routes.txt, and bicycle_routes.txt. No diffs in any.

**Comment by mandeepsandhu** [comment]
> I ran RAD against de_benchmark_routes.txt, demo_routes.txt (including auto and bus costing), pedestrian_routes.txt, and bicycle_routes.txt. No diffs in any.

Awesome! Thanks for running the extra validation! 🙏

**Pull request merged**
