### PR TITLE
Graphid - change from union to struct

### PR DESCRIPTION
**Pull request by dnesbitt61**
Seeing about a 10-15% improvement in pathfinding performance with this change. Internally GraphId now uses bit operations to form the individual fields for return in the access methods and set methods. Externally, places where the prior fields data member was accessed directly now access either the constructor, access methods, or set methods.

### CODE REVIEW

**Comment by dgearhart** [comment]
:ship:

**Comment by noblige** [comment]
@dnesbitt61 is this PR complete? would be interested to cherry-pick and try it on our target

**Comment by dnesbitt61** [comment]
@noblige - I think it is ready. We are just waiting to make sure there aren't any side effects with data creation (a small test seemed good). I was also waiting for @kevinkreiser to double check. But initial testing has looked good so we will likely merge it very soon.

**Comment by kevinkreiser** [comment]
:rocket:

**Comment by noblige** [comment]
@dnesbitt61 Thanks. I've checked these changes and not seeing any performance difference. Did you see 10-15% improvement when compiling with `-O2` (which is not default)?

**Comment by dnesbitt61** [comment]
@noblige Yes, we have seen similar results after doing more extensive testing. I saw repeatable 10% performance when running valhalla_run_route with the multi-run flag. This re-runs the path-finding logic the specified number of times and prints out the average time for just the path-finding. When doing full server testing with siege we did not see the performance improvement. In the past I have found that timing the path finding piece (dominant part of the route request) has been a good test indicator of performance. However, I think there are some memory access optimizations that may be occurring in this case that we do not see in the general case. Might be interesting to dig deeper and find the true cause of the observed performance change in this testing environment but it might just remain a mystery. @kevinkreiser  did some searching and did find that unions in C++ can impact register use so I assumed that was happening. Maybe that is only happening in this test case due to repeated access of the same data. At any rate, sorry for the premature excitement on our end (and likely yours) - always looking for the magic bullet to squeeze a bit more performance.

**Pull request merged**
