### PR TITLE
Remove some casts double to float and vice versa

### PR DESCRIPTION
**Pull request by dm-u**
Removed implicit casts to Point2 which is float when it used for consruction AABB2<PointLL> which is double.

### CODE REVIEW

**Review by kevinkreiser — APPROVED** [review]
nice clean up

**Review by kevinkreiser — CHANGES_REQUESTED** [review]
need to fix ci by running the `format.sh` script

**Comment by dm-u** [comment]
> WARNING: There was an error checking the latest version of pip.

**Comment by nilsnolde** [comment]
The output is a admittedly pretty confusing, but that's not the thing it complains about, it's
```
format...................................................................Failed
- hook id: format
- files were modified by this hook
```

You'll need to run scripts/format.sh to format the c++ code.

**Comment by dm-u** [comment]
> ```
> format...................................................................Failed
> - hook id: format
> - files were modified by this hook
> ```

The same code passed the checks successfully. A bit confusing.

**Comment by nilsnolde** [comment]
Same code, but different _formatting_, see the first 2 file diffs removing one line each, that's likely format.sh/clang-format

**Comment by dm-u** [comment]
[Got it](https://github.com/valhalla/valhalla/compare/1a08a81cd5993c7ecf01d2a36499a14fa435e207..85446e73d3a426462bf3766ac084fb9ec81eef76), thanks!

**Review by kevinkreiser — APPROVED** [review]

**Pull request merged**
