### PR TITLE
Remove the state type template parameter from ViterbiSearch

### PR DESCRIPTION
**Pull request by ptpt**
This PR is huge but no worry! This PR instantiates `IViterbiSearch<state_t>` with `StateId`, a simple identifier value that contains time information. See `valhalla/meili/stateid.h`. This is possible because internally the viterbi search algorithms only care about the IDs, and externally the map matching algorithm can always get the corresponding real state object associated with the given state IDs for computing transition costs and emission costs.

This change simplifies the codebase a lot, especially the use of the viterbisearch (see `test/viterbisearch.cc`) and the interpolation part in `meili/map_matcher.cc`. It would be worth for future development.

Some internal changes:

- added `IViterbiSearch::HasStateId` and `IViterbiSearch::AddStateId`
- dereferencing an `StateIterator` (from `IViterbiSearch::SearchPath`) gives a `StateId` instead of a `State` object. If no state found at that time, then the stateid is invalid.

The tests are passed but need more intergated tests. I will merge it into my development branch `tao` first when the PR gets approved.

### CODE REVIEW

**Comment by kevinkreiser** [comment]
there seems to be a build error here, so we cant yet merge this. i have another pr that does a bunch of random routes, makes a fake gps from that and then checks that map matching returns the same path. id love to run these changes through that but it seems there are a few issues. i'll see if i can fix the build error here which will allow me to review this pr as well.

**Comment by kevinkreiser** [comment]
i had missed a small change in my test wrt @dgearhart 's earlier pr, so ive just merged that into your branch so that it doesnt cause you troubles!

**Comment by ptpt** [comment]
This PR is on `tao`, a branch created older than current master. This makes it hard to review diffs with master. I'd love to rebase it on master and merge there if it gets well tested. @kevinkreiser WDYT?

**Comment by kevinkreiser** [comment]
oh no! im sorry! i didnt notice that! i had assumed that we were targeting master so that we could use the new tests that i put in place to check for regressions. because i had assumed that i merged master into this. im so sorry about that! let me see if i can undo what ive done...

**Comment by ptpt** [comment]
No it's fine. I also merged master into this branch. I can easily base the PR to master if you agree.

**Comment by kevinkreiser** [comment]
@ptpt it seems that you also merged master into this branch so i will let it alone!

**Comment by kevinkreiser** [comment]
yeah please i'm happy to target master! currently i'm experiencing this failure:

```
=== Testing actor ===
                      test_actor2017/07/18 19:41:44.279371 [ANALYTICS] locations_count::2
2017/07/18 19:41:44.279509 [ANALYTICS] costing_type::auto
2017/07/18 19:41:44.279866 [ANALYTICS] location_distance::0.217330km
2017/07/18 19:41:44.284589 [ANALYTICS] travel_mode::0
2017/07/18 19:41:44.304957 [ANALYTICS] admin_state_iso:: PA 
2017/07/18 19:41:44.304990 [ANALYTICS] admin_country_iso:: US 
2017/07/18 19:41:44.305191 [INFO] trip_path_->node_size()=5
2017/07/18 19:41:44.911541 [INFO] maneuver_count::2
2017/07/18 19:41:44.916596 [ANALYTICS] locations_count::2
2017/07/18 19:41:44.916650 [ANALYTICS] costing_type::auto
2017/07/18 19:41:44.916888 [ANALYTICS] location_distance::0.217330km
2017/07/18 19:41:44.919732 [ANALYTICS] travel_mode::0
2017/07/18 19:41:44.925529 [ANALYTICS] admin_state_iso:: PA 
2017/07/18 19:41:44.925570 [ANALYTICS] admin_country_iso:: US 
2017/07/18 19:41:44.925692 [INFO] trip_path_->node_size()=5
2017/07/18 19:41:44.926304 [INFO] maneuver_count::2
2017/07/18 19:41:44.932537 [ANALYTICS] costing_type::auto
2017/07/18 19:41:44.932814 [ANALYTICS] trace_size::2
2017/07/18 19:41:44.932838 [ANALYTICS] location_distance::0.217330km
2017/07/18 19:41:44.935262 [ANALYTICS] travel_mode::0

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff739334c in std::vector<valhalla::meili::StateId, std::allocator<valhalla::meili::StateId> >::push_back (this=0x0, __x=...)
    at /usr/include/c++/5/bits/stl_vector.h:915
915		if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)
(gdb) up
#1  0x00007ffff73904c0 in valhalla::meili::ViterbiSearch::AddStateId (this=0xcff318, stateid=...) at src/meili/viterbi_search.cc:213
213	  unreached_states_[stateid.time()].push_back(stateid);
```

**Comment by ptpt** [comment]
Got lots of warnings in CircleCI, but none in my machine. Any idea how to fix it?

```
./valhalla/meili/viterbi_search.h:235:7: warning: 'valhalla::meili::ViterbiSearch' has a field 'valhalla::meili::ViterbiSearch::queue_' whose type uses the anonymous namespace [enabled by default]
 class ViterbiSearch: public IViterbiSearch
```

**Comment by kevinkreiser** [comment]
@ptpt yep will fix in one sec

**Comment by ptpt** [comment]
Thanks @kevinkreiser!

The PR is ready for review and merge. I will document code as much as I can while it is in the review.

**Comment by kevinkreiser** [comment]
sounds great! im just about ready with mine as well!

**Comment by kevinkreiser** [comment]
@ptpt i made a bunch of conflicts in your pr here. ive just tried to fix those conflicts so we'll see how that goes. after that would you be ok with merging this?

**Pull request merged**
