### PR TITLE
Improve bss connections

### PR DESCRIPTION
**Pull request by xlqian**
In this PR, we improve the bss connections by:
- create a better shape
- assign the correct speed
- set the oppo_local_idx, so that the bss connection edge won't be considered as a U turn
- set the use etc...

In the old version, the bss connections looked like: 
Screenshot from 2019-09-26 16-09-04

With this PR:
Screenshot from 2019-09-26 16-20-06

### CODE REVIEW

**Comment by xlqian** [comment]
(I'll use this PR to figure out why build-debug crashes with error 137)

**Comment by kevinkreiser** [comment]
@xlqian thank you so much for looking into the OOM killer!

**Comment by xlqian** [comment]
This PR is ready to be reviewed, any feedback is welcomed :)

**Comment by kevinkreiser** [comment]
@xlqian let me know if this is ready for review, if not yet, no worries, i just wanted to make sure you werent waiting on us!

**Comment by xlqian** [comment]
This PR is ready to be reviewed, any feedback is welcomed :)

**Pull request merged**
