### PR TITLE
Update roundabout information

### PR DESCRIPTION
**Pull request by niroigen**
Hello I am a developer at a startup company called SmartHalo and we needed a requirement to get the exit angles within a roundabout, and this pull request would be able to return those angles. When on a roundabout the drive_on_right() property would be returned as well.

### CODE REVIEW

**Comment by dnesbitt61** [comment]
What is the impact of this PR? Does it change the route result or does it add information to a trace_attributes response? Are there documentation changes required to describe the changes to any response?

**Comment by niroigen** [comment]
The impact of this pull request is that it would add more information to the response. With this PR when entering a certain roundabout you would know whether you are on drive on right or left, as well as all the exits within the roundabout (including the ones that will not be entered). I wasn't quite sure if there should be some changes to the documentation, but if you feel like there should I would do them.

**Comment by dnesbitt61** [comment]
Can you give an example of what the response change looks like? If this is a change to the route result and narrative output there may be more work needed. I'll let @dgearhart take a look.

**Comment by niroigen** [comment]
[Examples.zip](https://github.com/valhalla/valhalla/files/2266912/Examples.zip)
Here is an example that contains an output that contains a roundabout, and one that doesn't

**Comment by dgearhart** [comment]
are the exit angles the spoke angles of the roundabout with respect to where one entered the roundabout?

**Comment by farough** [comment]
Yes, they are the angles with respect to the spoke, I believe they are always in counterclockwise direction.

**Comment by kevinkreiser** [comment]
@dgearhart any chance to review this, seems like a decent addition if we can get it in before it diverges too far from master.

**Comment by dgearhart** [comment]
@kevinkreiser i would really like to review/test - I just did not get to it yet

**Comment by niroigen** [comment]
I could possibly be working on this during the weekend if that would be alright with you @kevinkreiser?

**Comment by kevinkreiser** [comment]
@niroigen no rush, but i think we'd like to review it and get it merged whenever you are ready! thank you so much!

**Comment by dnesbitt61** [comment]
I accidentally closed this PR. I think the owner @niroigen may need to reopen?

**Comment by farough** [comment]
Niro was an intern at SmartHalo, but he has returned to school now. We thought the pull request might be merged before the end of his term. I've created a new pull request pointing to master here:
https://github.com/valhalla/valhalla/pull/1557

I can look into resolving the conflicts today or tomorrow.

**Comment by farough** [comment]
Sorry, the new pull request has a lot of extra commits in it, bare with me while I clean it up.

**Pull request closed without merging**
