### PR TITLE
add resize_file and create_directories

### PR DESCRIPTION
**Pull request by kevinkreiser**
this adds more mock support to our custom implementation of filesystem mimicking the std::filesystem form c++17. if we can get remove_directories in there we can probably remove boost::filesystem completely.

this stuff should work on windows so long as you have cygwin or mingw posix headers installed. if we just make that a requirement we can even remove that thirdparty library for dirent most likely.

### CODE REVIEW

**Comment by kdiluca** [comment]
:+1:

**Comment by mloskot** [comment]
> cygwin or mingw (...) if we just make that a requirement

Please, don't, please! I'll try to fix it with some `#ifdef`-s.

**Comment by kevinkreiser** [comment]
@mloskot no worries, you are our top windows contributor so we highly value your opinion on this! just let us know your thoughts on any of this!

**Comment by mloskot** [comment]
@kevinkreiser I've submitted some fixes in #1629

**Pull request merged**
