### PR TITLE
Readonly tarball indices should not require write permissions

### PR DESCRIPTION
**Pull request by LaGrunge**

### CODE REVIEW

**Comment by LaGrunge** [comment]
It seems Valhalla MinGW Build is broken inside environment setup
 Problem: conflicting requests
  - nothing provides mingw64(api-ms-win-core-synch-l1-2-0.dll) needed by mingw64-boost-1.75.0-1.fc34.noarch

**Comment by mandeepsandhu** [comment]
> It seems Valhalla MinGW Build is broken inside environment setup
> Problem: conflicting requests
> 
> * nothing provides mingw64(api-ms-win-core-synch-l1-2-0.dll) needed by mingw64-boost-1.75.0-1.fc34.noarch

Yes, you can ignore mingw64 build failures for now (the build environment is broken).

**Comment by LaGrunge** [comment]
> > * nothing provides mingw64(api-ms-win-core-synch-l1-2-0.dll) needed by mingw64-boost-1.75.0-1.fc34.noarch
> Yes, you can ignore mingw64 build failures for now (the build environment is broken).

Thank you! I have rebased my branch for current head, looking forward for review and possible merge

**Review by kevinkreiser — APPROVED** [review]

**Review by kevinkreiser — CHANGES_REQUESTED** [review]
Changlelog entry need moved up to the new section I believe

**Review by kevinkreiser — APPROVED** [review]

**Pull request merged**
