### PR TITLE
osmway struct update:  added up to 33 and not 32

### PR DESCRIPTION
**Pull request by gknisely**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by kevinkreiser** [comment]
this will greatly reduce the size of the sequence files we produce during parsing! did you git blame to figure out how this happened?

**Comment by gknisely** [comment]
> this will greatly reduce the size of the sequence files we produce during parsing! did you git blame to figure out how this happened?

@kevinkreiser Multiple updates in the struct from a few folks.  Including me!  I blame @gknisely .  lol

**Comment by kevinkreiser** [comment]
it was this one: https://github.com/valhalla/valhalla/pull/3132/files#diff-008839081832f497d56bd5db7a488a52e78c1386738390e126ce1b31e522054eR1739

**Review by kevinkreiser — APPROVED** [review]

**Comment by kevinkreiser** [comment]
no need to wait for CI the fix is obvious

**Comment by dnesbitt61** [comment]
Probably won't make a big difference in size (there are so many full uint32_t data members) but good find regardless!

**Pull request merged**
