### PR TITLE
Add cmath and cstdint headers where needed

### PR DESCRIPTION
**Pull request by TimRepke**
As discussed in valhalla/valhalla#659, GCC 5.4.0 does not contain these headers by default, so they have to be explicitly imported.
Changes in this PR are made by running:

```
for i in $(find . -name '*.cc' -or -name '*.cpp' -or -name '*.h'); do
grep -E 'std::abs' $i >& /dev/null && sed -ri '1 i #include <cmath>' $i
grep -E 'uint[0-9]+_t' $i >& /dev/null && sed -ri '1 i #include <cstdint>' $i
done
```

Without these changes it was not possible to compile the project using GCC 5.4.0 with std=C++11. This still does not support GCC 6.x.

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@TimRepke some of these files already have the file that you are including. can you adjust your `grep` to account for when the headers are already there? you can see on `src/baldr/geojson.cc` that it already had `cmath`

**Comment by kevinkreiser** [comment]
@TimRepke sorry for being so picky about this but, for the `cstdint` header a lot of the time this is put in the `.h` file and then the `.cc` file includes this `.h` file. so putting it in both is not needed. so if you've added cstdint to the header can you please remove it from the corresponding source file?

with cmath its kind of the opposite. in most cases itd only be needed in the source file unless we specifically call things like `std::floor` or `std::abs` for example in the header.

**Comment by kevinkreiser** [comment]
@TimRepke das ist doch Pettersson oder? meine Kinder lieben diesen Zeichentrick :+1:

**Comment by TimRepke** [comment]
@kevinkreiser ja, Petterson. Ich liebe die Bücher, auf die Bilder kann man stundenlang gucken und findet immer wieder neue Details. Zeichentrick habe ich nie gesehen...

Back to the topic: no worries about being picky! The code in this repository should stay clean and I'm by far not a C++ expert. I'll fix it tomorrow as I'm in the train without my computer.

**Comment by TimRepke** [comment]
Reverted the commits for a clean slate and ran the updated script:
```
#!/bin/bash
for i in $(find . -name '*.cc'); do
  if [ ! -z "$(grep -E 'std::abs' $i)" ] && [ "0" -eq "$(grep -o -c 'cmath' $i)" ]; then
    sed -ri '1 i #include <cmath>' $i
  fi

  hfile=$(echo $i | sed 's/\.cc/\.h/'|sed 's/src\//valhalla\//')
  if [ -f $hfile ]; then
    [[ ! -z "$(grep -E 'uint[0-9]+_t' $i)" ]] && [[ "0" -eq "$(grep -o -c 'cstdint' $hfile)" ]] && sed -ri '4 i #include <cstdint>' $hfile
  else
    [[ ! -z "$(grep -E 'uint[0-9]+_t' $i)" ]] && [[ "0" -eq "$(grep -o -c 'cstdint' $i)" ]] && sed -ri '1 i #include <cstdint>' $i
  fi
done

for i in $(find . -name '*.h'); do
  grep -E 'std::abs' $i >& /dev/null && sed -ri '4 i #include <cmath>' $i
done
```

**Comment by kevinkreiser** [comment]
this looks good ill try it out on my end and get it merged hopefully early next week. danke noch mal @TimRepke

**Pull request merged**
