### PR TITLE
Shortcut fix

### LINKED ISSUE #1484: Shortcuts can create inconsistent routes
hi everyone, i'm a sailfish os user, 
sailfish os has a navigation app which is called whogo maps, which uses open street map as maps provider and a program called osmscout for calcolating offline routes, maps and so on,
osmscout in turn uses valhalla for providing offline routes to whogo maps but it may happen it give the app some routes that are wrong or longer than expected. Considering whogo maps also support mapquest for online routing i decided to compare both valhalla and mapquest (both based on openstreetmap) and to my surprise mapquest gave me the exact route while valhalla a much longer one, and not correct due to street limitations not respected...why is that?

to give you a more concrete example, this is the exact route in mapquest

via migliori>via del popolo>via acquaviva>via dello splendore

while this is the one wrong in valhalla
via migliori>piazza della libertà>via vincenzo bindi>via 24 maggio>via filippo turati>via galileo galilei>via montello>via bertolino>viale dello splendore

This route is not only much longer but even unpraticable due to via bertolino being open only to church's processions

if you want to check both streets are in giulianova (abruzzo italy)

### LINKED ISSUE #1545: Not superseding regular edges in cases where shortcuts have been settled
The shortcut mask is not set unless the shortcut edge is used during the call to Expand from the node. This is NOT correct in the case where the shortcut edge has already been used and has been settled (the shortest path to the end of the shortcut edge has been found). In cases where a node is expanded due to a path from a different incoming directed edge, any previously settled shortcut edges will be skipped but the superseded edge will NOT be skipped as it should be.

Due to this, we are not realizing the full potential of shortcut edges in terms of performance. 

This impacts bidirectional A*, CostMatrix, A* (anywhere shortcuts are used).

### PR DESCRIPTION
**Pull request by dnesbitt61**
Update shortcut code to either use the shortcut or the regular edge. This should fix some inconsistencies in paths due to shortcut use vs. regular edge use. 

fixes #1484 

This PR also addresses a performance issue due to expanding regular edges when a shortcut has already been settled (least cost path found). By marking shortcut masks only if used the prior code allowed a path entering a node from a different inbound edge to expand regular edges that should have been superseded by an already settled shortcut edge. This leads to not realizing the full performance improvement that shortcuts afford. 

fixes #1545 

This PR improves performance on long distance routes by about 2X. 
Similar changes were made to CostMatrix - leading to a 2X improvement there as well (for a testw matrix with locations spread apart by up to 1000km).

This PR does change routes so some quality checks should be performed.

 - [x] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)
 - [x] Update relevant [documentation](docs/README.md)

### CODE REVIEW

**Comment by dnesbitt61** [comment]
Showing the inconsistent route is fixed:

image

image

**Comment by dgearhart** [comment]
were quality checks performed? or do they need to be run?

**Comment by dnesbitt61** [comment]
Need some opinions on some routes. They definitely differ. This fixes some inconsistencies as noted, but also leads to more shortcut use on intermediate routes (where before it would expand both shortcut and regular edge for some of the path)

**Comment by dgearhart** [comment]
@dnesbitt61 i will run some RAD tests this morning

**Comment by dgearhart** [comment]
delta seems acceptable

**Pull request merged**
