### PR TITLE
Do not use avoid edges as origin or destination

### PR DESCRIPTION
**Pull request by dnesbitt61**
Fixes a user submitted issue #1740. Do not use any avoided edges as origin or destination of a route, matrix, or isochrone.

Also fixed valhalla_run_matrix which had an issue reading service limits from the config file.

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by kevinkreiser** [comment]
is there any down side to doing this in the loki worker? like when loki finds the avoid edges should it then remove them from any locations edge sets? it would happen in one place then instead of in every algorithm. also it would give us a way to fail early if it turns out to have removed all the edges from a given location.

just a thought! otherwise looks good to me

**Comment by dnesbitt61** [comment]
If there is a central place in loki where this can be done then that makes sense to me.  I see loki::Search called within all the different actions so wouldn't this logic have to be added to each of those?

**Comment by kevinkreiser** [comment]
My suggestion was to do it where we add the avoids which is in a single location in the loki worker: https://github.com/valhalla/valhalla/blob/master/src/loki/worker.cc#L100

**Comment by dnesbitt61** [comment]
Unfortunately this is before Search is called for the individual actions.

**Comment by kevinkreiser** [comment]
maybe we just add the avoid locations to the call to `search` and have those results just exclude anything in that list

**Comment by danpat** [comment]
Filtering out edges in the loki search would make the behaviour strict, is that's what's desired, or is it more heuristic?

**Comment by dnesbitt61** [comment]
yes, these are hard avoids

**Comment by dnesbitt61** [comment]
It occurs to me that the behavior is not entirely correct as this is implemented. Any edge found as an avoid location will be disallowed as a path location (location provided for the route).  However, travel along the edge may be allowed if the path location position is "behind" the snapped avoid position (relative to the direction of travel for the edge). To be entirely proper, this PR should be updated to consider the distance along the edge for both the avoid location and the path location.

**Comment by dnesbitt61** [comment]
The determination of whether to exclude an edge that is part of a PathLocation needs to happen in thor since the logic differs depending on whether the edge is an origin edge (needs to exclude if the avoid location is ahead of the origin along the directed edge) or a destination (the reverse logic - the edge is excluded if the avoid location is behind or before the destination along the directed edge).

**Comment by dnesbitt61** [comment]
some test cases:
// Avoid location is behind the origin along W Orange St. This route should succeed
http://localhost:8002/route?json={"locations":[{"lat":40.040692,"lon":-76.294917},{"lat":40.040451,"lon":-76.297106}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.040809, "lon":-76.293750}]}

// Avoid location is ahead of the origin along W Orange St. This route should fail
http://localhost:8002/route?json={"locations":[{"lat":40.040809, "lon":-76.293750},{"lat":40.040451,"lon":-76.297106}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.040692,"lon":-76.294917}]}

// Avoid location is ahead of the destination along W Orange St. This route should succeed
http://localhost:8002/route?json={"locations":[{"lat":40.040809, "lon":-76.293750},{"lat":40.040451,"lon":-76.297106}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.040423,"lon":-76.297277}]}

// Two way street - avoid location ahead of origin, must go "around the block"
http://localhost:8002/route?json={"locations":[{"lat":40.042864, "lon":-76.296220},{"lat":40.042511,"lon":-76.299128}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.042733,"lon":-76.297218}]}

// Two way street - avoid location behind of origin, can go straight to the destination
http://localhost:8002/route?json={"locations":[{"lat":40.042733,"lon":-76.297218},{"lat":40.042511,"lon":-76.299128}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.042864, "lon":-76.296220}]}

// Two way street - avoid location before destination, must go "around the block"
http://localhost:8002/route?json={"locations":[{"lat":40.042511,"lon":-76.299128},{"lat":40.042840, "lon":-76.296209}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.042758, "lon":-76.297153}]}

// Two way street - avoid location after destination, can go straight to the destination
http://localhost:8002/route?json={"locations":[{"lat":40.042511,"lon":-76.299128},{"lat":40.042758, "lon":-76.297153}],"costing":"auto","directions_options":{"units":"meters"}, "avoid_locations":[{"lat":40.042840, "lon":-76.296209}]}

**Pull request merged**
