### PR TITLE
fiddling with tar_index test failures

### PR DESCRIPTION
**Pull request by kevinkreiser**
we have a long standing issue with the tar_index test which fails randomly on osx and arm. i'm going to play around with trying to fix it.. more to come later

### CODE REVIEW

**Comment by nilsnolde** [comment]
Got on intel OSX and ran this test 100 times in a loop, didn't fail once.. Is anything manipulating the utrecht tar in some other test, so parallel execution might be a problem? I did run `check` a few times as well, but didn't get any failure either..

**Comment by nilsnolde** [comment]
Coincidentally we havent' seen such a failure in > 1 week and quite a few builds.. :man_shrugging:

**Comment by kevinkreiser** [comment]
we should merge this, it is a bug in our test configuration. i cant explain how it would cause the issue we have, it doesnt seem enough but i havent had time to try to reproduce it and we may as well get this small fix

**Comment by kevinkreiser** [comment]
> so parallel execution might be a problem
yes the problem has to be something due to timing

**Comment by nilsnolde** [comment]
go for it. it's weird that there's times when it's not failing for weeks, and then it's failing randomly here and there for 1-2 weeks, and again pause for weeks. :shrug:

**Pull request merged**
