### PR TITLE
Serialization of costOption demo

### PR DESCRIPTION
**Pull request by debasis9658**
#3770 

 Added serilaizeCostOption function which will serilaize the costOption.

This is a demo function as I have only implemented the json formatting for only two attributes.

Review and comment

### CODE REVIEW

**Comment by nilsnolde** [comment]
Jep, goes in the right direction. Now you'll have to call that function in the action serializers. Eventually we'll have to overload the function you created with the variant [you had before](https://github.com/valhalla/valhalla/issues/3770#issuecomment-1416707909), I kinda forgot that most serializers are still using the legacy way.

I suggest you start with `route_serializer_valhalla.cc` which passes the same serializer class I asked you to use. Then write a small test in `test/gurka` which proves that the costing object is indeed returned on a route request. Have a look at other gurka tests, it's pretty self-explanatory. Then we can go ahead with the other actions.

**Comment by nilsnolde** [comment]
Also, you'll need to follow the dev guidelines: https://github.com/valhalla/valhalla/blob/master/CONTRIBUTING.md. As you can see CI is failing because the code is not formatted.

**Comment by debasis9658** [comment]
image
@nilsnolde kindly have a look at the screenshot. I am not able to resolve the error "git failed". I am in the git directory but it is still showing the error. How can it be resolved. Tried everything.

**Comment by nilsnolde** [comment]
You’re on Windows. Surprised you came this far. You’ll need Linux or Mac to develop Valhalla.

**Comment by debasis9658** [comment]
Yeah, Actually I am using linux virtual environment. Figured out that issue. Thanks @nilsnolde

**Comment by nilsnolde** [comment]
Are you still on this @debasis9658 ?

**Pull request closed without merging**
