### PR TITLE
remove notice from 2018

### PR DESCRIPTION
**Pull request by matkoniecz**
removes what was added in 2018 in https://github.com/valhalla/valhalla/commit/63bfd80090e8722bb6e8abc0242262196b191848
proposed in https://github.com/valhalla/valhalla/issues/2637#issuecomment-706288964

disclaimer: I know nothing about Valhalla

# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by mloskot** [comment]
I think it's fine to remove it as almost the same note is displayed here
https://github.com/valhalla/valhalla/blob/master/CHANGELOG.md#release-date-2018-11-21-valhalla-300

Perhaps this sentence in the `CHANGELOG.md` could be updated slightly based on the `README.md` one.

```
- This release changes the Valhalla graph tile formats.
+ This release changes the Valhalla graph tile formats to make the tile data more efficient and flexible.
```

**Comment by matkoniecz** [comment]
> Perhaps this sentence in the CHANGELOG.md could be updated slightly based on the README.md one.

Is it better fitting as a separate PR or as addition to this one?

**Comment by mloskot** [comment]
I'd stick it in this PR, as it is related.

**Comment by matkoniecz** [comment]
done

**Review by mloskot — APPROVED** [review]
LGTM :-)

**Comment by mloskot** [comment]
@kevinkreiser I'm curious, what does the `invalid` label mean if PR is still merged?

**Comment by kevinkreiser** [comment]
@mloskot it disqualifies a PR from counting in the hacktoberfest promotion. the idea is that trivial README updates are not really in the spirit of the event (ie a more meaningful contribution to an open source project). something like the other issue that was opened where we suggested to move the demos into the main repo and update the docs to properly reference/showcase them (maybe even doing a little work to unhide the options for hitting localhost) would be a more significant contribution, and is in my opinion, closer to what the point of hacktoberfest is about.

**Comment by mloskot** [comment]
@kevinkreiser I'm sorry, I completely missed the hacktoberfest here and not linked this PR as part of that initiative.
I completely agree (we've been applying similar policy in Boost, https://twitter.com/mloskot/status/1311381934770184193?s=19)

**Comment by kevinkreiser** [comment]
@mloskot no problem at all I marked the repo with hacktoberfest so by default all merged prs are eligible. I planned to use the invalid label for prs that shouldn't count toward it! Thanks again for all your contributions!

**Comment by mloskot** [comment]
@kevinkreiser Thanks. In Boost, we decided to use `spam` label :)

**Comment by matkoniecz** [comment]
Note that "invalid" was supposed to be used for spam PRs, someone with multiple "invalid" labels on their PRs would be banned (I remember mention of three triggering ban, but I am not sure now).

**Comment by kevinkreiser** [comment]
the documentation made no mention of that, please understand that i did not do it with the intent of banning you. i simply wanted to make sure the people with properly substantial PRs got credit for hacktoberfest

**Comment by matkoniecz** [comment]
> the documentation made no mention of that

Yeah, hacktoberfest was kind of organizational blowup with hasty mitigations around it. 

I even kind of suspect that the ban was just threatened in registration form and not implemented :)

**Pull request merged**
