### PR TITLE
Pedestrian crossings are allowed for bikes.

### PR DESCRIPTION
**Pull request by molind**
# Issue

Few more fixes for #3705 .

I've checked it on Belarus dump and now it works correctly.

### CODE REVIEW

**Comment by gknisely** [comment]
@molind Need to add to the test too.  Did you test locally too?

**Comment by molind** [comment]
Yes, only on local machine. Imported dump of belarus and tried to compute route from the issue.

**Comment by gknisely** [comment]
@molind I can't modify your branch, but I updated the test.  Can you add this to your branch under `valhalla/test/gurka` and delete the old test named `test_admin_sidewalk_override.cc`  Of course please push up the changes.  Thank you.

[test_admin_sidewalk_crossing_override.cc.gz](https://github.com/valhalla/valhalla/files/9616936/test_admin_sidewalk_crossing_override.cc.gz)

**Comment by gknisely** [comment]
@molind I forgot to mention that you need to update the changelog

**Comment by molind** [comment]
More like it's hangup somewhere in `make -C build -j8 coverage`

see bottom task in https://app.circleci.com/pipelines/github/valhalla/valhalla/9482/workflows/4fb8bf4b-7314-4303-b345-c78f7c336608/jobs/54247
`Too long with no output (exceeded 10m0s): context deadline exceeded`

**Comment by kevinkreiser** [comment]
@molind the lint-build-debug one is indeed failing because of a known issue which we can safely ignore: #3740 

whatever the osx build is though we cannot ignore

**Comment by nilsnolde** [comment]
Just realized that the OSX build error was already in `master` and came from the most recent PR at https://github.com/valhalla/valhalla/pull/3746. I guess that went unnoticed with lint/debug failing as well. Could you amend that when you have the time @gknisely ?

**Comment by kevinkreiser** [comment]
That's no good. While we are waiting for the elevation builder test to be fixed I think we should disable some of it so that we don't get in the habit of ignoring build statuses

**Comment by gknisely** [comment]
> Just realized that the OSX build error was already in `master` and came from the most recent PR at #3746. I guess that went unnoticed with lint/debug failing as well. Could you amend that when you have the time @gknisely ?
> 
> EDIT: Win is failing for the same reason as over here: [#3588 (comment)](https://github.com/valhalla/valhalla/pull/3588#issuecomment-1254111359)

@molind you will have to update your test with this small change.  https://github.com/valhalla/valhalla/pull/3757

**Comment by molind** [comment]
@gknisely done.

**Review by gknisely — APPROVED** [review]

**Pull request merged**
