### PR TITLE
Avoid shortcuts truck fix

### PR DESCRIPTION
**Pull request by ktatterso**
# Issue

The TestAvoidShortcutsTruck unit test always fails for me.  I did a little debugging... I'm not sure if this is a gurka  projection issue or if boost::geometry::intersect() is having trouble at the equator/prime-meridian. Either way, this is just a quick fix to get this test passing.

#fixes https://github.com/valhalla/valhalla/issues/3195

## Tasklist

 - [x] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by mandeepsandhu — APPROVED** [review]
lgtm

**Review by PureW — APPROVED** [review]
Nice, resolves https://github.com/valhalla/valhalla/issues/3195 for me

**Comment by nilsnolde** [comment]
Interesting.. wonder if it’s related to #3195 @PureW ? You wanna give this branch a shot? Was it the same error @ktatterso ?

**Comment by ktatterso** [comment]
> Interesting.. wonder if it’s related to #3195 @PureW ? You wanna give this branch a shot? Was it the same error @ktatterso ?

Yes, @PureW confirms it is the same.

**Comment by nilsnolde** [comment]
Urgh, didn’t see that. Great!

**Comment by nilsnolde** [comment]
Urgh, didn’t see that. Great!

**Pull request merged**
