### PR TITLE
#2032 fix wrong tag parsing by updating lua5.2 to lua5.3

### LINKED ISSUE #2032: Lua5.2 tag parser issue
Lua5.2 seems to have a bug that is not parsing road restrictions (width, length, height) correctly. The bug occurs in https://github.com/valhalla/valhalla/blob/92ce15a0efd17eb9a6f90e4cb845de1a9b42f091/lua/graph.lua#L718 and affects only floating values without a specific unit and having a zero after the decimal point e.g.: `2.0` and interprets it as an imperial.

`Problem`: Floating restrictions with a `X.0` value like `2.0` should be parsed as meters. The tag parser Script wrongly converts those meter values to feet like `2.0` to `0.61` with Lua5.2.

`Solution`: Change Lua dependency to Lua5.3. The bug that is causing this misinterpretation seems to be solved in Lua5.3. 

I would just update the readme and leave the rest to your team. Is that ok?

### PR DESCRIPTION
**Pull request by MichaelsJP**
Signed-off-by: Julian Psotta <julian@gis-ops.com>

fixes #2032 

Floating restrictions with floating point numbers e.g. X.0 value like 2.0 should be parsed as meters. The tag parser Script wrongly converts those meter values to feet like 2.0 to 0.61 with Lua5.2.
The fix is to simply update Lua5.2 to Lua5.3
https://github.com/valhalla/valhalla/issues/

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@MichaelsJP to make this real we should actually update CI to use newer lua. to do this we need to update the docker build image in the docker repository. you can see that here: https://github.com/valhalla/docker/blob/master/Dockerfile-build#L8

honestly we should probably move the docker stuff into this repo as well.

**Comment by MichaelsJP** [comment]
@kevinkreiser issue for moving the docker files into valhalla/valhalla https://github.com/valhalla/valhalla/issues/2067

**Comment by MichaelsJP** [comment]
Looks good I guess. I don't really get why the `codecov` is failing though. I didn't add any changes in code.

**Comment by danpat** [comment]
@MichaelsJP Do you know *why* upgrading to Lua5.3 fixes the parsing problem?  I ask because I've been experimenting with LuaJIT for performance improvements, but it only supports Lua5.1 syntax/builtins.

Would migrating to LuaJIT by default *also* fix this problem?

**Comment by danpat** [comment]
I fixed the root of the problem over in https://github.com/valhalla/valhalla/pull/2355

**Comment by danpat** [comment]
No longer needed - I fixed the root cause of the bug in https://github.com/valhalla/valhalla/pull/2355

If we change Lua, it'll probably be for LuaJIT which is faster.

**Pull request closed without merging**
