### PR TITLE
Updates googletest and robin-hood-hashing

### PR DESCRIPTION
**Pull request by PureW**
due to compile errors on clang 11.1.0, see individual commits for specific errors.

### CODE REVIEW

**Comment by merkispavel** [comment]
Hm, I'm getting linker error
- mac os catalina
- apple clang 12.0
```
FAILED: test/graphtileheader
: && ccache /usr/local/opt/ccache/libexec/c++ -fcolor-diagnostics  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000 test/CMakeFiles/graphtileheader.dir/graphtileheader.cc.o -o test/graphtileheader  test/libvalhalla_test.a  src/libvalhalla.a  /usr/local/lib/libprotobuf-lite.dylib  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurl.tbd  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd  /usr/local/lib/libprime_server.dylib  /usr/local/lib/libspatialite.dylib  /usr/local/opt/sqlite3/lib/libsqlite3.dylib  /usr/local/lib/libluajit-5.1.dylib  lib/libgtest_maind.a  lib/libgmockd.a  lib/libgtestd.a  -lpthread  /usr/local/lib/libgeos.dylib  /usr/local/lib/libgeos_c.dylib && :
Undefined symbols for architecture x86_64:
  "testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)", referenced from:
      testing::internal2::TypeWithoutFormatter<valhalla::midgard::GeoPoint<double>, (testing::internal2::TypeKind)2>::PrintValue(valhalla::midgard::GeoPoint<double> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in graphtileheader.cc.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by merkispavel** [comment]
> Hm, I'm getting a link error
> 
> * mac os catalina
> * apple clang 12.0
> 
> ```
> FAILED: test/graphtileheader
> : && ccache /usr/local/opt/ccache/libexec/c++ -fcolor-diagnostics  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000 test/CMakeFiles/graphtileheader.dir/graphtileheader.cc.o -o test/graphtileheader  test/libvalhalla_test.a  src/libvalhalla.a  /usr/local/lib/libprotobuf-lite.dylib  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurl.tbd  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd  /usr/local/lib/libprime_server.dylib  /usr/local/lib/libspatialite.dylib  /usr/local/opt/sqlite3/lib/libsqlite3.dylib  /usr/local/lib/libluajit-5.1.dylib  lib/libgtest_maind.a  lib/libgmockd.a  lib/libgtestd.a  -lpthread  /usr/local/lib/libgeos.dylib  /usr/local/lib/libgeos_c.dylib && :
> Undefined symbols for architecture x86_64:
>   "testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)", referenced from:
>       testing::internal2::TypeWithoutFormatter<valhalla::midgard::GeoPoint<double>, (testing::internal2::TypeKind)2>::PrintValue(valhalla::midgard::GeoPoint<double> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in graphtileheader.cc.o
> ld: symbol(s) not found for architecture x86_64
> ```

Got it. The cause is gtest needs to know how to print the object if you call EXPECT_EQ(lhs, rhs). As `PointLL` is a custom type without defined `ostream<<` operator  - it fails to link.
Options
1) Define `ostream<<` or function `PrintTo` so that gtest could print `PointLL` type. Cons: there is at least 1 similar error with `TransitSchedule` type. So I would prefer to ...
2) replace all `EXPECT_EQ(lhs, rhs)` with `EXPECT_TRUE(lhs == rhs)` for user types

**Comment by merkispavel** [comment]
ouch.. there are to many link errors, almost in every test file. Maybe we can remove `-Werror` from gtest compilation flags somehow?

**Comment by PureW** [comment]
> o know how to print the object if you call EXPECT_EQ(lhs, rhs).

Hmm womp womp. I guess this is new behaviour in Clang 12? As my clang 11.1 and whatever CI uses passes.

**Comment by PureW** [comment]
Closing this as the protobuf issue went away with Clang 12.

Robin-hood hash issue still remains though so I'll open a new PR at https://github.com/valhalla/valhalla/pull/3151 for that

**Comment by nilsnolde** [comment]
gtest is now doing this: https://github.com/valhalla/valhalla/issues/3157#issuecomment-865084006

introduced for gcc with 11.1.0 recently (on arch at least). 

`Maybe we can remove -Werror from gtest compilation flags somehow and stay with the current revision?` is there a reasonable way to do that? Or we'd have to suck it up working out all those link errors?

**Comment by merkispavel** [comment]
> Maybe we can remove -Werror from gtest compilation flags somehow and stay with the current revision? is there a reasonable way to do that?

I gave it a try but no success :( Maybe somebody who's native cmake-ish speaker can make it work

**Comment by merkispavel** [comment]
> Hm, I'm getting a link error
> 
> * mac os catalina
> * apple clang 12.0
> 
> ```
> FAILED: test/graphtileheader
> : && ccache /usr/local/opt/ccache/libexec/c++ -fcolor-diagnostics  -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names -pagezero_size 10000 -image_base 100000000 test/CMakeFiles/graphtileheader.dir/graphtileheader.cc.o -o test/graphtileheader  test/libvalhalla_test.a  src/libvalhalla.a  /usr/local/lib/libprotobuf-lite.dylib  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libcurl.tbd  /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libz.tbd  /usr/local/lib/libprime_server.dylib  /usr/local/lib/libspatialite.dylib  /usr/local/opt/sqlite3/lib/libsqlite3.dylib  /usr/local/lib/libluajit-5.1.dylib  lib/libgtest_maind.a  lib/libgmockd.a  lib/libgtestd.a  -lpthread  /usr/local/lib/libgeos.dylib  /usr/local/lib/libgeos_c.dylib && :
> Undefined symbols for architecture x86_64:
>   "testing::internal2::PrintBytesInObjectTo(unsigned char const*, unsigned long, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)", referenced from:
>       testing::internal2::TypeWithoutFormatter<valhalla::midgard::GeoPoint<double>, (testing::internal2::TypeKind)2>::PrintValue(valhalla::midgard::GeoPoint<double> const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*) in graphtileheader.cc.o
> ld: symbol(s) not found for architecture x86_64
> ```

There were uninstalled gtest headers in the system directories that caused the link errors https://github.com/valhalla/valhalla/pull/3166#issuecomment-867048431

**Pull request closed without merging**
