### PR TITLE
Do not add clones to ViterbiSearch to fix segfault

### PR DESCRIPTION
**Pull request by dgearhart**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@ptpt im writing up an issue on this. there is a problem with topk that when it does the kth pass where k is > 0 it segfaults because it tries to use invalid ids (the ones on the claimed states). it looks to me like you were trying to single that it was already used in the code but we couldnt find where you were making use of it.

**Comment by ptpt** [comment]
I get it. I didn't consider the case for invalid state ID.

Fixing...

**Comment by dgearhart** [comment]
did not work properly

**Comment by ptpt** [comment]
Do you have a test case that fails?

**Comment by kevinkreiser** [comment]
@dgearhart does perhaps he can paste it in here?

**Comment by dgearhart** [comment]
@ptpt Here is test case that failed:
    auto matched = json_to_pt(actor.trace_attributes(
        R"({"costing":"auto","best_paths":3,"shape_match":"map_snap","shape":[
        {"lat":52.088548,"lon":5.15357,"accuracy":30},
        {"lat":52.088627,"lon":5.153269,"accuracy":30},
        {"lat":52.08864,"lon":5.15298,"accuracy":30},
        {"lat":52.08861,"lon":5.15272,"accuracy":30},
        {"lat":52.08863,"lon":5.15253,"accuracy":30},
        {"lat":52.08851,"lon":5.15249,"accuracy":30}]})"));

**Pull request closed without merging**
