### PR TITLE
Backport node bindings

### LINKED ISSUE #1412: Backport node bindings to 2.6
## Background

We are in the process of writing node bindings for Valhalla which expose all of the `tyr::actor` actions (i.e. `route`, `locate`, ...). We currently working toward a 3.0.0 release of Valhalla that will include some breaking changes, and are pushing the node bindings in that same direction. Ultimately, we would like to be able to publish a stable node module to the npm registry. As of last week, the `valhalla` namespace in npm was taken by another small package. The npm team agreed to transfer that package to us to be used by this project!  🎉 They have asked us to publish something to the package ASAP to prove our stake in the project, so we are going to publish an alpha release to get something up there.

## Backporting to 2.6.x

We are going to be [publishing release candidates _of 3.0.0_](https://github.com/valhalla/valhalla/pull/1411) to the npm registry as we have them, since that is the version we are currently sprinting toward. When we publish a 3.0.0 pre release, we will tag it in npm as `next`. That way, you will not download it by default when you run `npm install valhalla`. However, it could be useful to have a 2.6 version published as well, especially since _right now_ the `route` functionality matches 2.6 and does not contain breaking changes. 

We could do this by backporting the node bindings to the 2.6 branch, and tagging the 2.6.x package as `latest` in npm. This way, folks doing npm install valhalla would get 2.6.x. This is not on my immediate roadmap, but I may come back to it eventually. However, if someone else would like to take this on, please do so!

### PR DESCRIPTION
**Pull request by danpaz**
# Issue

Closes #1412. Backports the node bindings currently in master to the `2.6` release branch. 
PRs cherry picked include:
- https://github.com/valhalla/valhalla/pull/1342 (to fix OSX builds)
- https://github.com/valhalla/valhalla/pull/1341
- https://github.com/valhalla/valhalla/pull/1397
- https://github.com/valhalla/valhalla/pull/1400
- https://github.com/valhalla/valhalla/pull/1413
- https://github.com/valhalla/valhalla/pull/1414
- https://github.com/valhalla/valhalla/pull/1415
- [x] after it's merged: https://github.com/valhalla/valhalla/pull/1423 

## Tasklist

 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

**Comment by danpaz** [comment]
@kdiluca tagging you in for review on this one. 

Note the base branch on this PR is the [`2.6`](https://github.com/valhalla/valhalla/tree/2.6) branch. The goal is to be able to release a version of node bindings for Valhalla that's based on the latest stable release. After this PR merges v2.6.4 would become the first stable release with node bindings published.

**Comment by kevinkreiser** [comment]
is this waiting on #1467 ?

**Comment by allierowan** [comment]
@danpaz @kevinkreiser @kdiluca I brought in #1467 and #1457 and did a small refactor with @kevinkreiser to fix a rapidjson compile error. Would love a review!

**Comment by kevinkreiser** [comment]
master is no longer unstable :tada: this work is already present in master and we've recently released it as https://github.com/valhalla/valhalla/releases/tag/2.7.0 

as this targets 2.6 its no longer needed. thanks all!

**Pull request closed without merging**
