### PR TITLE
allow for the parsing of strings into number types

### PR DESCRIPTION
**Pull request by kevinkreiser**
recently we pushed out an update that neutered support for treating strings as numbers (boost property tree did that by default). we thought it would be cool to be more strict but it turns out some folks were taking advantage of our loose and dirty parsing. this reenables that but without reverting to using `boost::ptree` but instead using `boost::lexical_cast` (which is probably what ptree was using anyway..) 

@dgearhart @ecgreb

### CODE REVIEW

**Comment by ecgreb** [comment]
Thanks for the quick fix!

I created an issue here to tidy up our loose and dirty request syntax so future versions of On the Road and the Mapzen Android SDK will omit these quotes.

https://github.com/mapzen/on-the-road_android/issues/105

**Comment by gknisely** [comment]
:shipit:

**Comment by dgearhart** [comment]
:shipit:

**Comment by kevinkreiser** [comment]
@ecgreb thanks!

**Comment by ecgreb** [comment]
Created a pull request here https://github.com/mapzen/on-the-road_android/pull/107 to fix the request format on Android.

The values for `lat`, `lon`, and `heading` should no longer be wrapped in quotes when we send the request.

Converting `heading` from type `String` to `double` required some special handling to make sure we don't send a default heading of 0.0 when one has not been explicitly set but I think we have it working now!

**Pull request merged**
