### PR TITLE
Isotile optimization

### PR DESCRIPTION
**Pull request by dnesbitt61**
Generating isotiles can take several seconds for large contours (e.g. a 120 minute auto contour centered on a urban area like Washington, DC). Looking into this, it was noted that there was extraneous code to mark tiles using segments between shape points of an edge. Then there was code to mark the resampled polyline. It was suspected that when the resampling code was added the original marking code was not removed.

Other potential causes of low performance are the large number of trigonometry calls made within the resmaple_spherical_polyline method. A new method, resample_polyline, was added that does linear interpolation of points between the original polyline vertices. This also uses floating point trigonometric methods to improve performance.

Additionally, the IsoTile Intersect method was replaced with simply marking tiles that intersect the bounding box of the segment (rather than those that the segment intersects - using a Bresenham method to identify tiles touched by the line segment). 

These optimizations lead to generation times being cut nearly in half for a 2 hour test case centered in Washington,DC.

 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by kevinkreiser** [comment]
can you show images for the differences in results of smaller isochrones say a 5 10 15 min isochrone for bike or walk?

**Comment by dnesbitt61** [comment]
Pedestrian, 5,10,15,20 minute isochrones:

With optimizations:
isochrone1

Without (code from master):
isochrone2

**Comment by kevinkreiser** [comment]
what is generalization set to in t his? can you set it to 0. also can you do it in a less dense network?

**Comment by dnesbitt61** [comment]
Bicycle - generalization set to 50, with 15, 30, 45, 60 minute contours:

Master:
bicycle_isomaster

Optimizations
isobicycle_branch
:

**Comment by dnesbitt61** [comment]
Pedestrian 15 minute contour:

master:
ped_iso_master

branch:
ped_iso_branch

**Pull request merged**
