### PR TITLE
Swap VS for ninja on azure CI

### LINKED ISSUE #2778: Use ninja in azure jobs
I just tried ninja for the first time on windows and it cut down the compile time from ~20 mins to ~5 mins.. If there's no other serious drawbacks I'm not aware of we could swap compilers on CI.  

Also not sure if/how well etc VS can cache build files, but ninja is pretty good at it from all I saw so far, so we could even cache the build folder, that should get most win builds down to << 5 mins. any concerns @mloskot, @kevinkreiser ?

### PR DESCRIPTION
**Pull request by nilsnolde**
fixes #2778 

previous PR didn't update anymore for some reason (showing first signs of MSyndrome?)..

### CODE REVIEW

**Comment by nilsnolde** [comment]
Ok, I give up.. Build works locally _exactly like that_ in a clean PS environment.. was hard enough to find a workaround to even _use_ ninja on azure.. why it is not finding `cmath`, `limits` etc is beyond me.. if you have some clue @mloskot, appreciated. if not, I'll grudgingly dump this one

**Comment by kevinkreiser** [comment]
@nilsnolde it looks like for some reason it cant find stand headers like `<array>` and `<limits>` that makes me think there is something wrong with the include path its using. i know very little about the windows build but i think we can get this with some more debuging when we have time

**Comment by nilsnolde** [comment]
I was furious this morning! After 2 hours debugging and finally getting this disgraceful excuse of a shell to do the equivalent of a “source env” it can’t find stl stuff🤯 But i know I just gotta give it a few days to cool down 😉

**Comment by mloskot** [comment]
@nilsnolde I've just started reproducing the `.azure-pipelines.yml` commands in PowerShell console locally to see if I can find any clues, it's still installing the vcpkg packages for me.

I recall numerous issues with 'loading' the VS environment into PowerShell, issues with `vcvars64.bat` loading, and such.
In fact, locally, I never use PowerShell for VS but I always use the old black Command Prompt (CMD).
Hence, my experience with VS development environment inside PowerShell is very limited.

Perhaps, switching from `powershell` to `cmd` for the `'Run CMake to configure build'` step would make the whole lot of change? 🤔

**Comment by mloskot** [comment]
I have managed to build the `master` inside PowerShell following the `.azure-pipelines.yml` from this PR:

Here is the complete sequence of my commands:

```
❯ get-history

  Id     Duration CommandLine
  --     -------- -----------
   1        0.010 cd D:\valhalla\
   2        5.096 git pull
   3       55.039 git submodule update --init --recursive
   4    30:54.931 D:\vcpkg\vcpkg.exe install --triplet x64-windows "@.vcpkg_deps.txt"
   5        0.110 D:\vcpkg\vcpkg.exe list
   6        0.021 cp third_party\OSM-binary\src\fileformat.proto third_party\OSM-binary\src\fileformat.proto.orig
   7        0.024 cp third_party\OSM-binary\src\osmformat.proto third_party\OSM-binary\src\osmformat.proto.orig
   8        0.019 echo 'syntax = "proto2";' > third_party\OSM-binary\src\fileformat.proto
   9        0.023 type third_party\OSM-binary\src\fileformat.proto.orig >> third_party\OSM-binary\src\fileformat.proto
  10        0.014 echo 'syntax = "proto2";' > third_party\OSM-binary\src\osmformat.proto
  11        0.024 type third_party\OSM-binary\src\osmformat.proto.orig >> third_party\OSM-binary\src\osmformat.proto
  12        0.010 rm third_party\OSM-binary\src\fileformat.proto.orig
  13        0.010 rm third_party\OSM-binary\src\osmformat.proto.orig
  14        0.010 $env:Path += "C:\bin"
  15        0.911 ninja --version
  16        0.043 &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" version
  17        0.010 $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
  18        0.039 $vcvarspath = &$vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
  19        0.010 Write-Output "vc tools located at: $vcvarspath"
  20        0.841 cmd.exe /c "call `"$vcvarspath\VC\Auxiliary\Build\vcvars64.bat`" && set > %temp%\vcvars.txt"
  21        0.040 Get-Content "$env:temp\vcvars.txt" | Foreach-Object {…
  22        4.091 cl /?
  23        0.035 mkdir _build
  24        0.049 cmake --version
  25       11.880 cmake -G Ninja -S. -B_build -DCMAKE_TOOLCHAIN_FILE="D:\vcpkg\scripts\buildsystems\vcpkg.cmake" -DVCPKG_APPLOCAL_DEPS=ON -DENABLE_DATA_TOOLS=ON -DENABLE_TOOLS=ON -DENABLE_PYTHON_BINDINGS=ON -DENABLE_TESTS=OFF -DENABLE…
  26     1:19.388 cmake --build _build --config Release
  27        0.078 .\_build\valhalla_build_tiles.exe --version
```

The last command output:

```
❯ .\_build\valhalla_build_tiles.exe --version
valhalla_build_tiles 3.0.9
```

**Comment by nilsnolde** [comment]
thanks @mloskot I had the same experience locally.. which is why I get so frustrated with CI not replicating that. 

> Perhaps, switching from powershell to cmd for the 'Run CMake to configure build' step would make the whole lot of change?

jep, I'll try that now. I opted for powershell for the wget & unzip convenience, but that can be done before cmake invocation.

> In my local build, I noticed, that for Ninja generator the %BUILD_DIR%\%BUILD_CFG%\ paths below should read just %BUILD_DIR%\:

Cool, saves me at least one commit:)

**Comment by nilsnolde** [comment]
sweet @mloskot changing to cmd did make all the difference! Will still fail now (didn't update the exe commands yet), but it builds:)

**Comment by nilsnolde** [comment]
Ah finally azure skipped a build! even if not wanted... so the CI skips seem to be:
- CircleCI: [ci skip] anywhere
- Azure: [ci skip] **in the very beginning**
- GH actions: no native way :roll_eyes:

**Comment by mloskot** [comment]
https://www.appveyor.com/docs/how-to/filtering-commits/
> NOTE: AppVeyor searches for skip commit string in the commit message title only 

It's a total mess. An excellent (and sad) example of a lack of interoperability for a very trivial feature

**Comment by nilsnolde** [comment]
I really do like to skip as many CI builds as possible. The power waste is HUUGGEEE! Researching for #2793 , how come no provider ever thought of making that easier, saving tons of $$$! Eventually I'd like the repos I commit to to only build before merging, CI shouldn't be used for "is my commit clean?", implement proper pre-commit/-push hooks. It's not only CI provider's responsibility but every dev's.

**Comment by mloskot** [comment]
CircleCI has this feature of fan-in/fan-out workflows that are useful for that: if core part does not compile, don't build anything that dependes on core, etc. https://twitter.com/mloskot/status/984834302482542592

Here is current example https://app.circleci.com/pipelines/github/boostorg/geometry/111/workflows/a494fd59-a4c1-4a6e-bd08-602dc6878fde

**Comment by mloskot** [comment]
```
C:\ProgramData\chocolatey\bin\c++.exe -DAUTO_DOWNLOAD=0 -DBOOST_NO_CXX11_SCOPED_ENUMS -DHAS_REMOTE_API=0 -DNOGDI -DRAPIDJSON_HAS_STDSTRING -DWIN32_LEAN_AND_MEAN -ID:/a/1/s -ID:/a/1/s/valhalla -ID:/a/1/s/third_party/date/include -ID:/a/1/s/third_party/rapidjson/include -ID:/a/1/s/third_party/dirent/include -ID:/a/1/s/vcpkg/installed/x64-windows/include -Isrc/mjolnir -Isrc/mjolnir/valhalla -Isrc -Isrc/valhalla -ID:/a/1/s/vcpkg/installed/x64-windows/include/luajit -ID:/a/1/s/third_party/robin-hood-hashing/src/include -fdiagnostics-color=auto  -O3 -DNDEBUG -mfpmath=sse -msse2 -std=gnu++14 -MD -MT src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmpbfparser.cc.obj -MF src\mjolnir\CMakeFiles\valhalla-mjolnir.dir\osmpbfparser.cc.obj.d -o src/mjolnir/CMakeFiles/valhalla-mjolnir.dir/osmpbfparser.cc.obj -c D:/a/1/s/src/mjolnir/osmpbfparser.cc
D:/a/1/s/src/mjolnir/osmpbfparser.cc:34:10: fatal error: netinet/in.h: No such file or directory
 #include <netinet/in.h>
          ^~~~~~~~~~~~~~
compilation terminated.
```

No idea what is the `C:\ProgramData\chocolatey\bin\c++.exe`, but isn't it the MinGW?
That would make  `#if defined(_WIN32) && !defined(__MINGW32__)` is false.

By the way, `_WIN32` is macro defined by MSVC compiler, while `WIN32` is defined by Windows SDK.

**Comment by nilsnolde** [comment]
```
CMake suite maintained and supported by Kitware (kitware.com/cmake).
-- The CXX compiler identification is GNU 8.1.0
-- The C compiler identification is GNU 8.1.0
```

oh man.. I figured it magically would use mvsc when using `cmd`. need to run vcvarsxxx.bat stuff again I guess..

**Comment by nilsnolde** [comment]
when it should run the executables, it reports
```
##[error]Cmd.exe exited with code '-1073741515'.
```
apparently that error code is for missing dll's (among others).. no idea what it would be missing

**Comment by nilsnolde** [comment]
fiiiiinally it worked! hope the incremental builds will work too..

**Comment by nilsnolde** [comment]
hmm, weird, incremental build doesn't work. it caches the build folder, successfully hits the cache and... starts from scratch :thinking:

**Review by mloskot — APPROVED** [review]
LGTM

I don't have experience with incremental builds on Azure Pipelines, so I can't tell what's wrong there.

**Comment by nilsnolde** [comment]
well, anyways, almost halfed the build time. and probably my life expectation dealing with this ;)

**Comment by mloskot** [comment]
@nilsnolde Undoubtly you've done quite a journey and patience testing, kudos :)

**Review by kevinkreiser — APPROVED** [review]

**Pull request merged**
