### PR TITLE
WIP: Avoid LogLevel clash with Win32 common macros with unfortunate names

### PR DESCRIPTION
**Pull request by mloskot**
# Issue

Further refinement to PR #1120

By the way, [push_macro and pop_macro are also supported by GCC](https://gcc.gnu.org/onlinedocs/gcc/Push_002fPop-Macro-Pragmas.html), so I hope they are also available for MinGW.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

### CODE REVIEW

**Comment by mloskot** [comment]
Dropping the solution as suboptimal

**Comment by kevinkreiser** [comment]
We could just rename them all universally to like VALHALLA_ERROR VALHALLA_WARN etc?

**Comment by mloskot** [comment]
@kevinkreiser That would be a PITA saver. Shall I submit PR?

**Comment by kevinkreiser** [comment]
Yeah I don't see why not we definitely don't want to clash with other common macros

**Pull request closed without merging**
