### PR TITLE
Enable auto-update on homebrew and upgrade xcode

### LINKED ISSUE #3036: Update homebrew to avoid downloads from bintray (which is shutting down)
[bintray is shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). `homebrew` has already [moved off of it](https://brew.sh/2021/04/12/homebrew-3.1.0/).

However, our osx executor is using an older version, which is causing failures of osx builds.

We should update homebrew before using it and also upgrade to the [newest xcode](https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions) version available from circle.

### PR DESCRIPTION
**Pull request by mandeepsandhu**
Update homebrew to newer version to avoid downloads from bintray which
is shutting down.

Also update to newest xcode version.

Fixes #3036

### CODE REVIEW

**Comment by mandeepsandhu** [comment]
@kevinkreiser looks like osx CI is now failing to build prime_server: https://app.circleci.com/pipelines/github/valhalla/valhalla/6469/workflows/7b233573-d282-499d-b0f4-a8d8c0883e15/jobs/42189

There a couple of ruby errors that I don't know what to make of. Let me know if you want me to try something.

**Comment by kevinkreiser** [comment]
interesting! i have no clue about that error but i'm sure after a bit of googling we can get to the bottom of it!

**Comment by mandeepsandhu** [comment]
> interesting! i have no clue about that error but i'm sure after a bit of googling we can get to the bottom of it!

it seems to be related to the homebrew update. wonder if the warning `homebrew-cask is a shallow clone` has fudged things up before the cask gets read later.

**Comment by kevinkreiser** [comment]
we recently updated xcode on ci and though it wasnt painless it wasnt too bad, while doing that we also made doing the upgrade slightly easier. going to close this since we arent suffering from this problem anymore

**Pull request closed without merging**
