### PR TITLE
Add support for LuaJIT

### PR DESCRIPTION
**Pull request by danpat**
# Issue

Migrates to LuaJIT for lua scripting.  Speeds up the `parse` phase of `valhalla_build_tiles` by about 12%.

```
# Before
$ /usr/bin/time ./valhalla_build_tiles -c config.json --start parse --end parse bulgaria-latest.osm.pbf
       38.91 real        35.94 user         1.91 sys
# After
$ /usr/bin/time ./valhalla_build_tiles -c config.json --start parse --end parse bulgaria-latest.osm.pbf
       30.35 real        28.23 user         1.61 sys
```

## Tasklist

 - [x] Add LuaJIT to test environment on CI to make sure it's not totally borked.
 - [ ] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by PureW** [comment]
If I remember correctly, we migrated to Lua 5.2. Do we have unittests that would catch any differences between 5.2 and the 5.1 version used by LuaJIT?

**Comment by kevinkreiser** [comment]
@danpat https://github.com/valhalla/valhalla/pull/2066 may be related and mentions problems with 5.2 vs 5.3

**Comment by danpat** [comment]
We have an interesting dependency problem here.  The Linux builds use the Docker image `valhalla/build:latest`, which contains the new LuaJIT dependencies.  However, a new version of that image won't get published until this PR is merged.

**Comment by danpat** [comment]
@gknisely hol-up - macOS is still failing.  If you merge this, all macOS builds in all branches are going to fail.

**Comment by gknisely** [comment]
@danpat it isn't.  

image

**Comment by gknisely** [comment]
The issue was out of mem.  Previous [pr](https://github.com/valhalla/valhalla/pull/2339) helped out with this for the tests.

**Pull request merged**
