### PR TITLE
Multiple CMake fixes for missing Protobuf and Boost requirements

### PR DESCRIPTION
**Pull request by mloskot**
Configure custom `protobuf:: targets` only if CMake <3.7.

Add missing dependency on `libprotobuf` target to some modules:
- `valhalla_module` does not seem to generate `valhalla::proto` `target_link_libraries`-linked against Protobuf targets
- clients of `valhalla::proto` do not transitively receive   include directories, etc.

Add missing Boost::boost where modules #include Boost headers.
Add missing dependency of baldr on third-party dirent.
Configure `libvalhalla.pc` only if `PKG_CONFIG_FOUND`
Call Unix-specific CMake command `create_symlink` only if UNIX.

Add MSVC-specific fixes to cmake/Binary2Header.cmake:

- add alternative workaround based on generating concatenated string literal to allow  sub 64K byte long string literals
- since 64K may be not enough, restore `xxd -i` behaviour (see minimal CMake configuration in #1124).

Note, although not specific to Windows, those are helpful when building Valhalla on Windows or any environment where Protobuf or Boost are not deployed in standard prefixes eg. `/usr` or `/usr/local`, where they can be found even if target dependencies configuration is incomplete.

# Issue

- #1604

## Tasklist

 - [ ] Review - you must request approval to merge any PR to master
 - [ ] Generally use squash merge to rebase and clean comments before merging

### CODE REVIEW

**Comment by mloskot** [comment]
@kevinkreiser FYI, I'm still applying some tweaks to this PR

**Comment by mloskot** [comment]
@kevinkreiser This is ready for review now.

Together with the bunch of recent MSVC-specific PRs, it restores support for building on Windows with VS2017.

**Comment by kevinkreiser** [comment]
@mloskot amazing work we owe you a :beer: and then some!

**Comment by mloskot** [comment]
Thanks :) The patch is yet to be checked at runtime - this or next week. I'm not sure of the Header2Binary thing is still sound. I'll welcome any feedback of course.

**Comment by kevinkreiser** [comment]
@mloskot I see that you still have `Boost::boost` on all the modules rather than just on `mjolnir`. This shouldn't be necessary. All of the modules other than `mjolnir` don't actually link boost, they just include the some of the header-only parts of boost. Does the windows build fail when you remove the boost dependency from say `baldr` for example?

**Comment by kevinkreiser** [comment]
@mloskot ok, ill try it again! last time i did this i noticed that it was adding the linker bits on linux which is not desirable. I haven't pulled this down in a while so let me do that!

**Comment by mloskot** [comment]
I think that would be a `FindBoost.cmake` bug if `Boost::boost` added any linker flags. The behaviour of that target is well documented:

https://github.com/Kitware/CMake/blob/08da4f8d70cce97a9a6913d74e6c128ca6c0a40b/Modules/FindBoost.cmake#L73-L75

https://github.com/Kitware/CMake/blob/08da4f8d70cce97a9a6913d74e6c128ca6c0a40b/Modules/FindBoost.cmake#L1992-L1999

**Comment by kevinkreiser** [comment]
I havent forgotten about this I just havent gotten to it yet. I'll get this merged in the next week or so! Sorry for the delay!

**Comment by mloskot** [comment]
@kevinkreiser No rush, thanks.

**Comment by kevinkreiser** [comment]
I'm going to merge this and deal with any downstream issues in a separate PR this has hanged out there long enough. Sorry for the wait @mloskot and thank you for your continued contributions to windows builds!

**Pull request merged**
