### PR TITLE
Adds distance to max distance error

### PR DESCRIPTION
**Pull request by jackrea07**
# Issue

This PR is targeting issue #3722 

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 N/A

##

### CODE REVIEW

**Comment by nilsnolde** [comment]
Easily the issue with the most PRs😂 And still not quite.. 

You can go through the comments of the others, some hints in there.

**Comment by jackrea07** [comment]
I was also having trouble building on Windows, I noticed the previous contributor could not do it either.
I found the valhalla_exception_t struct with a constructor that allows the passing of the code, message, http_code, etc. But the circleci throws an error saying the HTTP_400 is not defined in the statement I edited. Would you happen to know why?
Sorry, this is my first time contributing to open source, same as the previous contributor.

**Comment by nilsnolde** [comment]
I think you should first make your build work and set up your IDE properly. Helps a lot while developing. 

out of curiosity: is this Hacktober?

**Comment by nilsnolde** [comment]
superseded by #3779

**Pull request closed without merging**
