### PR TITLE
isolate prime_server dependencies to work function of loki worker

### PR DESCRIPTION
**Pull request by kevinkreiser**
this is a first step in making the workers usable from an embedded application without the need for prime_server bits.

i want flesh this out more before we merge it. specifically:

- review/change the inputs and outputs of the newly exposed member functions of the loki (and other) workers
- ifdef out the work function based on embedded flag in configure
- instantiate workers inside of the navigator and hook up top level methods on navigator to call functions on those workers and coordinate specific request types
- add the hookup for the interrupt on the navigator top level methods

after i do the above 3, we should have a decent template to do the thor, odin, and tyr workers (we may skip the tyr worker or replace the tyr worker with navigator entirely)

### CODE REVIEW

**Comment by kevinkreiser** [comment]
@noblige i have a rough draft going here ^^

**Comment by noblige** [comment]
looks good so far!

**Comment by noblige** [comment]
@kevinkreiser how is it looking? any chance to finalize this week?

**Comment by kevinkreiser** [comment]
@noblige I just wanted to let you know that I've updated the PR with all of the prime_server stuff separated out. Now you can do `--enable-services=no` and it wont require prime_server (and therefore zmq). The easy entry point for getting a route then is to instantiate an `actor_t` object and call `::route` or any of the others like `::trace_route`. You'll notice that currently only those two have tests so the obvious next steps are to actually write tests for the other actions the actor can perform.

**Comment by dnesbitt61** [comment]
:+1:

**Comment by kevinkreiser** [comment]
yeah its because of the low stress bike pr. easy fix, will get it in just a minute

**Pull request merged**
