### PR TITLE
Fix API reference docs table formatting

### PR DESCRIPTION
**Pull request by wcedmisten**
# Issue

fixes https://github.com/valhalla/valhalla/issues/3787

## Tasklist

N/A

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

N/A

### CODE REVIEW

**Review by nilsnolde — APPROVED** [review]
yeah, github has a _very_ forgiving markdown parser. that doesn't play well with most others.

**Comment by nilsnolde** [comment]
cancelled the jobs manually

**Comment by wcedmisten** [comment]
@nilsnolde Should I update the changelog for this? Is there a way to skip that CI check?

**Comment by nilsnolde** [comment]
> Should I update the changelog for this?

No need.

> Is there a way to skip that CI check?

Not sure if circleci respects a `[ci skip]` in the commit message, I think by now they all do. You can try that, if it doesn't work, don't worry.

**Review by nilsnolde — APPROVED** [review]

**Review by kevinkreiser — APPROVED** [review]

**Pull request merged**
