### PR TITLE
CI: Run build_and_publish job only if repository owner is valhalla

### LINKED ISSUE #4407: Add fork restrictions to GHA
When people are PR'ing from their master, GHA is currently running the crazily long docker workflow on their fork, which will obviously fail to push after it built the images.

### PR DESCRIPTION
**Pull request by mahdihasnat**
# Issue

Fixes #4407

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by mahdihasnat** [comment]
Hi @nilsnolde ,
This small check solves the issue. Please review.

**Comment by nilsnolde** [comment]
good point, thanks.. probably all other workflows would benefit from that too. would you mind adding those as well while you're at it?

**Comment by mahdihasnat** [comment]
But other workflows are not triggered on `push`.  So, I can't really verify the action after modification.

**Comment by nilsnolde** [comment]
Na you're right, the only other one who's on `push` already has that line. The new tz workflow is also useful for forks maybe.

**Review by nilsnolde — APPROVED** [review]

**Comment by mahdihasnat** [comment]
Never mind, I can still add this repository owner check and try to run the workflow manually.

**Comment by nilsnolde** [comment]
It's fine as-is, no worries.

**Pull request merged**
