### PR TITLE
Fixes to make batch.sh run correctly

### LINKED ISSUE #2139: Make run_route_scripts/batch.sh macos compatible
`run_route_scripts/batch.sh` in its current form does not work on macos/Darwin. It has the following issues:
1. Long options are not available in macos/Darwin distributions
2. Need an equivalent of `nproc` on macos/Darwin.
3. Newer bash syntax does not work on Mac's older bash version (`3.x`)
4. One `sed` command (`sed -i -e "s;$;|--config|${CONF};g" -e ...`) fails to run

1 & 2 can be fixed by installing `coreutils` package. 3 can be fixed by updating `bash` from *homebrew*. 4 will need a slight code-change.

Bonus:
This script is setting `set -o errrexit ...` at the beginning. This causes the error message when detecting `parallel` installation to be suppressed. This option should be moved further down after basic checks are done so that the error messages can be displayed to the user.

### PR DESCRIPTION
**Pull request by mandeepsandhu**
# Issue

The last sed command in this script was creating a malformed json. It
was stripping the trailing single-quote of the json string but not the
leading one.

Changed the sed expression to remove single quotes from the json string.
Also moved adding the "--config" option to the place where parallel is
invoking valhalla_run_route. Since the arg to this option is fixed for
all runs of parallel, I find it easier to read if placed in the same
place where the executable is being called. This also limits the sed
expression to whats needed.

Tested by running batch.sh as follows:
$ ./batch.sh ../test_requests/demo_routes.txt ../build/valhalla.json
and verifying that guidance instructions are generated in results/ dir.

Fixes #2139 

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by mandeepsandhu** [comment]
@danpaz @dgearhart can I request you both to try this change on your respective setups, to be sure I haven't broken something?

I've verified this change with a single route (for `Utrecht`, since I'm still downloading planet tiles). I'll be running a bigger set of routes once planet download completes.

**Comment by dgearhart** [comment]
> @danpaz @dgearhart can I request you both to try this change on your respective setups, to be sure I haven't broken something?

It does not work on linux - all the narrative files are empty

**Comment by mandeepsandhu** [comment]
> > @danpaz @dgearhart can I request you both to try this change on your respective setups, to be sure I haven't broken something?
> 
> @mandeepsandhu It does not work on linux - all the narrative files are empty

Hmmm. I'll need to see the output of `valhalla_run_route` and the json being fed to it, to know why its failing. Can you try this patch:
```
diff --git a/run_route_scripts/batch.sh b/run_route_scripts/batch.sh
index 33abb1f5d..3335562b7 100755
--- a/run_route_scripts/batch.sh
+++ b/run_route_scripts/batch.sh
@@ -53,11 +53,11 @@ sed -i -e "s/'//g" "${TMP}"
 #from the log messages otherwise every line will be a diff
 #TODO: add leading zeros to output files so they sort nicely
 echo -e "\x1b[32;1mWriting routes from ${INPUT} with a concurrency of ${CONCURRENCY} into ${RESULTS_OUTDIR}\x1b[0m"
-cat "${TMP}" | parallel --progress -k -P "${CONCURRENCY}" "valhalla_run_route {} --config ${CONF} 2>&1 | tee -a ${RESULTS_OUTDIR}/{#}.tmp | grep -F NARRATIVE | sed -e 's/^[^\[]*\[NARRATIVE\] //' &> ${RESULTS_OUTDIR}/{#}.txt; grep -F STATISTICS ${RESULTS_OUTDIR}/{#}.tmp | sed -e 's/^[^\[]*\[STATISTICS\] //' &>> ${RESULTS_OUTDIR}/{#}_statistics.csv; rm -f ${RESULTS_OUTDIR}/{#}.tmp"
+cat "${TMP}" | parallel --progress -k -P "${CONCURRENCY}" "valhalla_run_route{} --config ${CONF} 2>&1 | tee -a ${RESULTS_OUTDIR}/{#}.tmp | grep -F NARRATIVE | sed -e 's/^[^\[]*\[NARRATIVE\] //' &> ${RESULTS_OUTDIR}/{#}.txt; grep -F STATISTICS ${RESULTS_OUTDIR}/{#}.tmp | sed -e 's/^[^\[]*\[STATISTICS\] //' &>> ${RESULTS_OUTDIR}/{#}_statistics.csv; #rm -f ${RESULTS_OUTDIR}/{#}.tmp"
 # On macos, sed inline replace (-i opt) ends up creating a backup file with
 # "-e" suffix, even though -i arg is empty. The wildcard below will ensure that
 # that file is deleted as well.
-rm -f ${TMP}*
+#rm -f ${TMP}*
 echo "orgLat, orgLng, destLat, destLng, result, #Passes, runtime, trip time, length, arcDistance, #Manuevers" > ${RESULTS_OUTDIR}/statistics.csv
 cat `ls -1v ${RESULTS_OUTDIR}/*_statistics.csv` >> ${RESULTS_OUTDIR}/statistics.csv
 rm -f ${RESULTS_OUTDIR}/*_statistics.csv
```

Once applied, can you paste the contents of one of the `.tmp` files created alongside the `.txt` file (it has the o/p of executing `valhalla_run_route`)

**Comment by dgearhart** [comment]
> Once applied, can you paste the contents of one of the `.tmp` files created alongside the `.txt` file (it has the o/p of executing `valhalla_run_route`)

@mandeepsandhu below is the info after applying the patch:

## Run output
``` bash
./run.sh ../test_requests/demo_routes.txt 
Writing routes from ../test_requests/demo_routes.txt with a concurrency of 4 into results/20200110_100737_demo_routes
Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.


Computers / CPU cores / Max jobs to run
1:local / 4 / 4

Computer:jobs running/jobs completed/%of started jobs/Average seconds to complete
local:4/0/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/1/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/2/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/3/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/4/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/6/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
/bin/bash: valhalla_run_route-j: command not found
local:4/8/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
/bin/bash: valhalla_run_route-j: command not found
local:4/9/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/10/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/11/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/12/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/13/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/14/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/15/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/16/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/17/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:4/18/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:3/19/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:2/20/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:1/21/100%/0.0s /bin/bash: valhalla_run_route-j: command not found
local:0/22/100%/0.0s 
```
## *.tmp file contents
``` bash
cat *.tmp
/bin/bash: locations:[lat:40.794025: command not found
/bin/bash: locations:[lat:40.298355: command not found
/bin/bash: locations:[lat:40.298355: command not found
/bin/bash: locations:[lat:39.168583: command not found
/bin/bash: locations:[lat:40.285185: command not found
/bin/bash: locations:[lat:39.28679: command not found
/bin/bash: locations:[lat:40.6250142: command not found
/bin/bash: locations:[lat:40.7641292: command not found
/bin/bash: locations:[lat:34.094161308223335: command not found
/bin/bash: locations:[lat:34.0942323860854: command not found
/bin/bash: locations:[lat:40.650105: command not found
/bin/bash: locations:[lat:34.0942323860854: command not found
/bin/bash: locations:[lat:34.094646: command not found
/bin/bash: locations:[lat:40.794838: command not found
/bin/bash: locations:[lat:40.642948: command not found
/bin/bash: locations:[lat:40.310005: command not found
/bin/bash: locations:[lat:40.748428: command not found
/bin/bash: locations:[lat:40.265369: command not found
/bin/bash: locations:[lat:40.518681: command not found
/bin/bash: locations:[lat:40.038132: command not found
/bin/bash: locations:[lat:40.441692: command not found
/bin/bash: locations:[lat:40.285488: command not found
```

**Comment by mandeepsandhu** [comment]
@dgearhart whenever you have time, can you try this patch again? I believe it works for Linux now  (I tested in `docker/ubuntu-18.04`). The issue was my first patch removing `-C '\|` option which is used by `parallel` to parse the input (`{}`) correctly. On macOS, the `sed` express on [line 45](https://github.com/valhalla/valhalla/blob/master/run_route_scripts/batch.sh#L45), is not adding the `|` (not sure why) so this problem didn't manifest itself on it. Thanks for your help!

**Comment by mandeepsandhu** [comment]
@dgearhart I've tested this change on Linux (`ubuntu 19.10`), and its running successfully (tested with `test_requests/demo_routes.txt`). Let me know if you have any concerns around the change and/or testing.

**Pull request merged**
