### PR TITLE
Fix broken links in matrix API docs

### PR DESCRIPTION
**Pull request by mandeepsandhu**
# Issue

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by merkispavel — DISMISSED** [review]
Nice, thanks!

**Review by ktatterso — APPROVED** [review]

**Comment by mandeepsandhu** [comment]
@kevinkreiser OSX builds are failing again. I got this error initially:
```
Error: The contents of the SDKs in your Command Line Tools (CLT) installation do not match the SDK folder names.
A clean reinstall of Command Line Tools (CLT) should fix this.

Remove the broken installation before reinstalling:
  sudo rm -rf /Library/Developer/CommandLineTools

Install the Command Line Tools for Xcode 11.3.1 from:
  https://developer.apple.com/download/more/
```
Updating xcode to 11.3.1 fails prim_server build in a different manner:
```
configure.ac:2: error: possibly undefined macro: m4_esyscmd
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

Any idea on how to fix this? Or if its not-trivial to fix, maybe make osx optional again?

**Comment by gknisely** [comment]
> @kevinkreiser OSX builds are failing again. I got this error initially:
> 
> ```
> Error: The contents of the SDKs in your Command Line Tools (CLT) installation do not match the SDK folder names.
> A clean reinstall of Command Line Tools (CLT) should fix this.
> 
> Remove the broken installation before reinstalling:
>   sudo rm -rf /Library/Developer/CommandLineTools
> 
> Install the Command Line Tools for Xcode 11.3.1 from:
>   https://developer.apple.com/download/more/
> ```
> 
> Updating xcode to 11.3.1 fails prim_server build in a different manner:
> 
> ```
> configure.ac:2: error: possibly undefined macro: m4_esyscmd
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> ```
> 
> Any idea on how to fix this? Or if its not-trivial to fix, maybe make osx optional again?

@kevinkreiser I was going to disable macosx temporarily, but following the doc at https://circleci.com/docs/2.0/enable-checks/#to-disable-github-checks-for-a-project I am not seeing the `Update CircleCI Checks repository access page`  Do you?  If so, can you disable for now?

**Comment by kevinkreiser** [comment]
@gknisely yeah i can disable it, y ou just do it in the branch protection section on github for the repo. it will still build and fail but it wont block merging

**Comment by kevinkreiser** [comment]
should be good to go now

**Comment by gknisely** [comment]
> should be good to go now

ty @kevinkreiser

**Comment by mandeepsandhu** [comment]
> should be good to go now

thank you @kevinkreiser ! :pray:

**Review by gknisely — DISMISSED** [review]

**Review by ktatterso — APPROVED** [review]

**Pull request merged**
