### PR TITLE
Fix int_ref processing when building ways

### PR DESCRIPTION
**Pull request by mandeepsandhu**
# Issue
`int_ref`s were not being processed when `use_direction_on_ways_` was not set. This is a bug as `int_ref` should always be processed irrespective of that setting.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by kevinkreiser — APPROVED** [review]
Looks right to me. Why was that in there in the first place?

**Review by dgearhart — CHANGES_REQUESTED** [review]
build failures

**Comment by mandeepsandhu** [comment]
> Looks right to me. Why was that in there in the first place?

https://github.com/valhalla/valhalla/pull/3446/files#diff-5fcdff37eb551f814e2a44f24f9c6bcc37856bb8dadbbcb59e93d173e46c1132L1903 has been there since #2285 I beleive.

**Comment by mandeepsandhu** [comment]
Fix for the remaining CI error: https://github.com/valhalla/valhalla/pull/3450

**Comment by mandeepsandhu** [comment]
`test_create_extracts` fails with this change. The exact error is:
```
/usr/bin/python3.8 -m unittest discover -s /root/project/test/scripts -v
test_add_leaf_types (test_valhalla_build_config.TestBuildConfig) ... ok
test_nested_config (test_valhalla_build_config.TestBuildConfig)
tests if we get the values of nested dicts ... ok
test_override_config (test_valhalla_build_config.TestBuildConfig)
tests end to end if the arg parsing is working ... ok
test_get_tiles_with_bbox (test_valhalla_build_elevation.TestBuildElevation) ... ok
test_get_tiles_with_geojson (test_valhalla_build_elevation.TestBuildElevation) ... ok
test_get_tiles_with_graph (test_valhalla_build_elevation.TestBuildElevation) ... ok
test_create_extracts (test_valhalla_build_extract.TestBuildExtract) ... FAIL

======================================================================
FAIL: test_create_extracts (test_valhalla_build_extract.TestBuildExtract)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/project/test/scripts/test_valhalla_build_extract.py", line 26, in test_create_extracts
    self.check_tar(EXTRACT_PATH, exp_tuples, tile_count * INDEX_BIN_SIZE)
  File "/root/project/test/scripts/test_valhalla_build_extract.py", line 36, in check_tar
    self.assertIn(t, exp_tuples)
AssertionError: (2560, 25568, 290368) not found in ((2560, 25568, 289288), (293888, 410441, 658856), (954368, 6549282, 6051320))

----------------------------------------------------------------------
Ran 7 tests in 0.101s

FAILED (failures=1)
```

@gknisely could it have been due to int_ref's being processed now?

@nilsnolde do you know how the values expected in the test were constructed?

**Comment by gknisely** [comment]
> `test_create_extracts` fails with this change. The exact error is:
> 
> ```
> /usr/bin/python3.8 -m unittest discover -s /root/project/test/scripts -v
> test_add_leaf_types (test_valhalla_build_config.TestBuildConfig) ... ok
> test_nested_config (test_valhalla_build_config.TestBuildConfig)
> tests if we get the values of nested dicts ... ok
> test_override_config (test_valhalla_build_config.TestBuildConfig)
> tests end to end if the arg parsing is working ... ok
> test_get_tiles_with_bbox (test_valhalla_build_elevation.TestBuildElevation) ... ok
> test_get_tiles_with_geojson (test_valhalla_build_elevation.TestBuildElevation) ... ok
> test_get_tiles_with_graph (test_valhalla_build_elevation.TestBuildElevation) ... ok
> test_create_extracts (test_valhalla_build_extract.TestBuildExtract) ... FAIL
> 
> ======================================================================
> FAIL: test_create_extracts (test_valhalla_build_extract.TestBuildExtract)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/root/project/test/scripts/test_valhalla_build_extract.py", line 26, in test_create_extracts
>     self.check_tar(EXTRACT_PATH, exp_tuples, tile_count * INDEX_BIN_SIZE)
>   File "/root/project/test/scripts/test_valhalla_build_extract.py", line 36, in check_tar
>     self.assertIn(t, exp_tuples)
> AssertionError: (2560, 25568, 290368) not found in ((2560, 25568, 289288), (293888, 410441, 658856), (954368, 6549282, 6051320))
> 
> ----------------------------------------------------------------------
> Ran 7 tests in 0.101s
> 
> FAILED (failures=1)
> ```
> 
> @gknisely could it have been due to int_ref's being processed now?
> 
> @nilsnolde do you know how the values expected in the test were constructed?

@mandeepsandhu yes.  update the test please

**Review by dgearhart — APPROVED** [review]
:ship: thanks @mandeepsandhu

**Pull request merged**
