### PR TITLE
swap VS for ninja and set up build cache [ci skip]

### LINKED ISSUE #2778: Use ninja in azure jobs
I just tried ninja for the first time on windows and it cut down the compile time from ~20 mins to ~5 mins.. If there's no other serious drawbacks I'm not aware of we could swap compilers on CI.  

Also not sure if/how well etc VS can cache build files, but ninja is pretty good at it from all I saw so far, so we could even cache the build folder, that should get most win builds down to << 5 mins. any concerns @mloskot, @kevinkreiser ?

### PR DESCRIPTION
**Pull request by nilsnolde**
fixes #2778  

What issue is this PR targeting? If there is no issue that addresses the problem, please open a corresponding issue and link it here.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by nilsnolde** [comment]
Actually considering ditching x86 for Win as well. For ninja it apparently needs quite workaround, the little resources one finds here are mentioning to build your own toolchain file for VS.. Don't think I wanna dump a full day into this;)

@mloskot did you ever build with ninja on MS for x86? Or, even better, can we ditch the x86 CI builds? No idea if 32bit Win is still a thing (on servers maybe?)..

**Comment by mloskot** [comment]
> @mloskot did you ever build with ninja on MS for x86?

Yes, I have.

> Or, even better, can we ditch the x86 CI builds?

I don't mind.
I locally build Valhalla for x86 on daily basis, the latest release only, so if I notice any failure, I'll report & fix it.

> No idea if 32bit Win is still a thing (on servers maybe?)..

No idea really.
I use the x86 build as an extra check for overall extended code hygiene, to catch warnings, as compiler paranoid check :)

**Comment by nilsnolde** [comment]
Thanks @mloskot ! What do you think @kevinkreiser? I sorta doubt there's productive x86 MS systems around still and I didn't see the x86 Azure build give any other result than x64 so far..

**Comment by kevinkreiser** [comment]
@nilsnolde i have the same view as @mloskot does. we use the x86 builds to make sure we arent making any common mistakes around assuming integer types have a certain width or that our floating point math is robust enough to work on 32bit platforms.

i was writing this in another thread on another pr but i think the only worth while platforms with 32bit architectures that we would be targetting would be arm based ones. i think it makes sense to retire both the linux and windows x86 variants and open up a new issue to build a 32bit arm variant (probably with `DATA_TOOL=Off` set)

**Comment by nilsnolde** [comment]
Yeah you actually left that note in the issue to this PR:) I thought you're talking about linux only, so wanted to get matheusz's view on the win build.

anyways, glad to hear that, then I'll retire the x86 build on Azure.

**Comment by kevinkreiser** [comment]
can we do them all in one blast in a separate pr?

**Comment by nilsnolde** [comment]
jep sure, will do

**Comment by kevinkreiser** [comment]
@nilsnolde rock on, ill write the issue about adding back a limited arm one to get 32bit coverage

**Comment by nilsnolde** [comment]
github bug.. doesn't recognize last (hope last ever!) commit in this PR.. closing and reopening..

**Pull request closed without merging**
