### PR TITLE
Add missing boost::filesystem dependency to baldr

### PR DESCRIPTION
**Pull request by rinigus**
This PR addresses issue #2065 by adding Boost::filesystem to baldr dependencies. 

Dependency is induced by graphtile.cc

### CODE REVIEW

**Comment by rinigus** [comment]
I may know why the tests are failing. Working on getting it fixed

**Comment by rinigus** [comment]
Looks like all tests have passed. Please review as you are ready

**Comment by kevinkreiser** [comment]
@rinigus we were trying to keep the service running components free of linking boost... it looks like we mistakenly did not do that or that some versions of boost have the stuff in headers while others have it in libs... if we have no other choice ill merge this but id rather just undo whatever usage we have. ill take a look

**Comment by rinigus** [comment]
Sounds reasonable. I have my local builds with that enabled to make them possible. If we can avoid boost linking in that part, it would be better. Feel free to reject this PR if you find a better solution.

**Comment by kevinkreiser** [comment]
this one is no longer valid now that we've fixed it by removing boost::filesystem in #2081

**Pull request closed without merging**
