### PR TITLE
reduce required boost version to 1.51, related to #715

### PR DESCRIPTION
**Pull request by rinigus**

### CODE REVIEW

**Comment by kevinkreiser** [comment]
did all of the tests pass in this environment?

**Comment by rinigus** [comment]
No, I didn't do any tests (from tests) as such, I just run `valhalla_route_service`. How I am supposed to use your tests? Is there any configure / make option?

Note that I don't have data tools enabled. These require spatialite and I would prefer not to start porting it for the tests only :)

**Comment by kevinkreiser** [comment]
to run the tests do: `make test` can you paste the output here?

**Comment by rinigus** [comment]
Sure. Just give me 1-2 days. It has to be recompiled again in virtual machine with ARM emulation - not the fastest compilation. As soon as ready, I'll paste the output here .

**Comment by kevinkreiser** [comment]
no problem, thank you!

**Comment by rinigus** [comment]
Not 100%

```
PASS: test/logging
PASS: test/point2
PASS: test/distanceapproximator
PASS: test/aabb2
PASS: test/obb2
PASS: test/linesegment2
PASS: test/vector2
PASS: test/polyline2
FAIL: test/pointll
PASS: test/ellipse
PASS: test/encode
PASS: test/tiles
PASS: test/sequence
PASS: test/util_midgard
PASS: test/gridded_data
FAIL: test/location
PASS: test/admin
PASS: test/datetime
PASS: test/directededge
PASS: test/double_bucket_queue
PASS: test/edge_elevation
PASS: test/edgecollapser
PASS: test/laneconnectivity
PASS: test/graphid
PASS: test/tilehierarchy
PASS: test/graphtile
PASS: test/nodeinfo
PASS: test/turn
FAIL: test/graphreader
PASS: test/streetname
PASS: test/streetname_us
PASS: test/streetnames
PASS: test/streetnames_us
PASS: test/streetnames_factory
PASS: test/json
PASS: test/verbal_text_formatter
PASS: test/verbal_text_formatter_us
PASS: test/verbal_text_formatter_us_co
PASS: test/verbal_text_formatter_us_tx
PASS: test/factory
PASS: test/geometry_helpers
PASS: test/grid_range_query
PASS: test/grid_traversal
PASS: test/map_matcher_factory
PASS: test/queue
PASS: test/routing
PASS: test/viterbi_search
PASS: test/geojson_reader
PASS: test/geojson_writer
PASS: test/util_skadi
PASS: test/sample
PASS: test/skadi_service
PASS: test/loki_service
PASS: test/maneuversbuilder
FAIL: test/narrativebuilder
PASS: test/enhancedtrippath
PASS: test/sign
PASS: test/signs
FAIL: test/util_odin
PASS: test/narrative_dictionary
PASS: test/edgestatus
PASS: test/optimizer
PASS: test/thor_service
PASS: test/attributes_controller
PASS: test/astar
PASS: test/serializers
PASS: test/traffic_matcher
============================================================================
Testsuite summary for valhalla 2.2.3
============================================================================
# TOTAL: 67
# PASS:  62
# SKIP:  0
# XFAIL: 0
# FAIL:  5
# XPASS: 0
# ERROR: 0
```

**Comment by rinigus** [comment]
Just as an additional note: tests were run in virtual machine using ARM ScratchBox2. To run that all on phone would be a bit difficult - phone is not the best env to compile things. Usually, if there are issues with the virtualization then that would lead to a crash of VM. This has not happened here, so probably its "just" failure of the tests. One Gentoo (64 bit), all tests pass.

**Comment by kevinkreiser** [comment]
each test produces a log file like: `test/util_odin.log`. for the ones that failed could you show the contents of the logs? i'm wondering if some of them like `pointll` would have failed anyway due to floating point precision stuff (in other words ignorable because boost is not related to the failure).

what i was most worried about was that odin tests would fail (they more heavily rely on regex). so like `narrativebuilder` and `util_odin`. `graphreader` and `location` failing are pretty serious sounding too. can you paste the logs?

once i find the time i can dig deeper myself on a vm where i can source install boost 1.51. that might be a while though (a month probably). id say if its working to your liking, feel free to keep working with your fork patched to allow older boost.

we can keep this pr open until its resolved. thanks again!

**Comment by rinigus** [comment]
Here are the logs. Bunch is related to locale, as far as I can see. 

[graphreader.log.txt](https://github.com/valhalla/valhalla/files/1007906/graphreader.log.txt)
[location.log.txt](https://github.com/valhalla/valhalla/files/1007907/location.log.txt)
[narrativebuilder.log.txt](https://github.com/valhalla/valhalla/files/1007909/narrativebuilder.log.txt)
[pointll.log.txt](https://github.com/valhalla/valhalla/files/1007908/pointll.log.txt)
[util_odin.log.txt](https://github.com/valhalla/valhalla/files/1007910/util_odin.log.txt)

**Comment by kevinkreiser** [comment]
interesting so it seems we didnt even get to the point of seeing if regex was fine because of locales failing. i think this is expected. we use very debian specific way to test locale stuff (didnt want to roll our own). id say all of this looks ok to me except the one that one location test failure but that one i think might be the width of integers on your platform. in which case they all see ok to me.

when i get free time ill make a vm install boost 1.51 on it and see what that does then we can merge this. thanks!

**Comment by rinigus** [comment]
thanks! I tested `util_odin` on the device and it failed with the same locale errors. So, I guess something is wrong with locale handling. It could be down to the fact that I am generating locale on my PC (`./make_locales.sh *.json > ../genfiles/locales.h`) since I don't have `jq` command on the virtual machine.

Looking forward to see your test results.

**Pull request merged**
