### PR TITLE
OSRM serializer: Add voiceLocale to route if voice_instructions option is set

### LINKED ISSUE #4677: osrm_serializers: add `voiceLocale` to `routes`
When generating `voiceDirections` within the OSRM serializer, the locale should be indicated within each of the routes under the `voiceLocale` key. This will improve the quality of the generated audio in the MapLibre navigation SDK.

### PR DESCRIPTION
**Pull request by eikes**
Fixes #4677

When adding the voice_Instructions option for the OSRM serializer I missed that the JSON `routes` should also get an attribute, namely the `voiceLocale` which is simply the same as the language option that is passed in. 

## Tasklist

 - [x] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [x] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by eikes** [comment]
@kevinkreiser Can you help me here by triggering a CI rebuild? It seems like it stalled in an unrelated place...

**Comment by eikes** [comment]
Segmentation fault on windows when building tiles cannot be related to this change in the serializer...

```
D:\a\_temp\0b6bfbe1-f49e-48c3-b1ab-3f4aa4abffae.sh: line 2:   140 Segmentation fault      ./build/$BUILD_TYPE/valhalla_build_tiles.exe -c ./test/win/valhalla.json ./test/data/utrecht_netherlands.osm.pbf
```

**Comment by eikes** [comment]
@kevinkreiser can you maybe rerun the Windows CI pipeline?

**Comment by kevinkreiser** [comment]
if windows doesnt pass and it is indeed just during tile building then yeah we can review and get this merged and open another issue for intermittant windows build failures. i agree its not related to your work here

**Review by kevinkreiser — APPROVED** [review]

**Pull request merged**
