### PR TITLE
New Use=kService - identifies generic service roads

### LINKED ISSUE #2418: Bicycle Routes taking Service Roads to cut Corners
Amazon Logistics is adding service roads in my area in what I would call an incomplete manner. They started properly adding highway:service, service:driveway, access:private to driveways. Recently this pattern seems to be abandoned with most additions just being highway:service. Most of these are private driveways and some are service roads for businesses and restaurants.

Driving routes will generally avoid service roads even if they are incorrectly tagged since low speeds are generally applied to service roads. Bicycle routing is different as speed on a bicycle depends more on elevation changes than the type of road. 

To avoid taking service roads we need to properly identify them. The general road classification for service roads is service/other, where other includes cycleways, footways, tracks and other road types that bicycles can often use. Penalizing based on road classification will not work. What is needed is a road Use that differentiates highway:service tagged ways from regular roads. It turns out that there are road Uses for several types of service roads: Alleys, Driveways, Drive-Through, Emergency, Parking Aisle. However, these require OSM service tags in addition to the highway:service tag.

A possible solution is to create a generic Service road Use and assign any highway:service tagged OSM way that does not have additional service tagging to this road Use.

Then in the dynamic costing for bicycle routing a transition penalty can be applied when entering a Use=Service road. This should reduce occurrences of bicycle routes cutting through service roads near intersections as in the example below:

Screenshot from 2020-06-10 08-22-08

The path taken is over an abandoned (and clearly marked) road section that is currently used to get to driveways, but is not a through road. Other examples in the area cut through a restaurant parking area (which actually has a chain gate to prevent thru traffic). Since we cannot control the OSM editors making these changes we should protect against bad routes caused by these improperly tagged "service" roads.

### PR DESCRIPTION
**Pull request by dnesbitt61**
Add Use:kService for generic highway=service roads where there are no service tags to specialize the use to driveway, alley, parking aisle, etc. This new use separates service roads from other road uses and allows use of this information in costing.

A penalty is applied in bicycle costing when transitioning to a service road (from a non-service road). This penalty defaults to 15 seconds, and can be configured per request if needed (like many other costing options).

# Issue

Primary issue this addresses is cutting corners using service roads.
fixes #2418 

## Tasklist

 - [x] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by dnesbitt61** [comment]
This simply separates highway:service from other road uses (where there are no service tags to specialize the type of service road). Next step is to use this in bicycle costing to fix routes that cut corners (this happens mostly with bicycle routes since they do not use road speed much when choosing the best path).

**Comment by kevinkreiser** [comment]
using #2418 as a guide i think it will be quite easy for us to make a quick gurka test to prove that this works. let me know if you want me to chip in and add that!

**Comment by dnesbitt61** [comment]
I am working on it, but first I see a couple other tests failing. I see code in graphenhancer that checks for use==kRoad that might be changing some logic.

**Comment by dnesbitt61** [comment]
working Gurka test! However, the isochrone test fails. I expect the costing change to make small differences in bicycle routing, but I also think the auto test is failing and I don't know why yet!

**Comment by dnesbitt61** [comment]
I updated the failing auto isochrone test with the new result. I viewed both the prior result and the new result with geojson.io and the contour shape is nearly identical.

**Comment by dnesbitt61** [comment]
Updated/merged master into this branch and fixed the Gurka test. What else might be needed to merge?

**Review by kevinkreiser — APPROVED** [review]
this looks good to me, @gknisely any reservations?

**Comment by gknisely** [comment]
> this looks good to me, @gknisely any reservations?

Can't think of anything.  :shipit:

**Pull request merged**
