### PR TITLE
Add TopKSearch (in progress)

### PR DESCRIPTION
**Pull request by ptpt**
Still in progress.

The proposed usage of `TopKSearch`:

```c++
ViterbiSearch vs;
TopKSearch ts(vs);
for (int k=1; k <= top_k; k++) {
    best_path[k] = vs.SearchPath(time);
    ts.RemovePath(time); // or ts.RemovePath(best_path[k])
}
```

### CODE REVIEW

**Comment by ptpt** [comment]
TODO:

1. [ ] add `void IViterbiSearch::AppendStateId(StateId::Time time)` to append an state ID at `time`
2. [ ] add `void IViterbiSearch::ClearSearch()` to reset the search but keep the added stateids
3. [ ] test `TopKSearch`

**Comment by kevinkreiser** [comment]
i can add the test for this in the meantime if you like? let me know if that would be helpful for you!

**Comment by ptpt** [comment]
@kevinkreiser would be nice to start writing tests for it though it's not ready.

The idea is we should have a function that can brute force list all paths in order of path costs.

```c++
using Column = std::vector<StateId>;
using EmissionCostMap = std::unordered_map<StateId, float>;
using TransitionCostMap = std::unordered_map<StateId, std::unordered_map<StateId, float>>;

// make sure that
// for (Time time=0; time < columns.size(); time++) {
//    for each stateid in column: assert stateid.time() == time;
// }
std::vector<Column> generate_graph();

// emission cost of state A can get by map[A] (if A has emission cost)
// cost must be non-negative
EmissionCostMap generate_emission_map();

// transition cost from state A to state B can get by map[A][B] (if there is an transition in between).
// cost must be non-negative
EmissionCostMap generate_transition_map();

// make sure search space is small so it's able to list all
std::vector<std::vector<StateId>> list_paths(
const std::vector<Column>& columns,
const EmissionCostMap& emission_costs,
const TransitionCostMap& transition_costs);

```

with this helper function, we can compare if the k-th path have the same cost with the topksearch
```c++

auto paths = list_paths(generate_graph(), generate_emission_map(), generate_transition_map());
for (auto& path: paths) {
    assert total_cost(path) == total_cost(vs.SearchPath(time));
    ts.RemovePath(time);
}
```

**Comment by kevinkreiser** [comment]
@ptpt i was going to do something simpler and less of a unit test but more of an integration tests. specifically i was going to add another test case to the mapmatch test file with a path that has lets say 3 points. the first 2 points are directly on the same edge and the 3 point is between two edges where the road forks. id move the point closer to the one edge vs the other. then id check the street names from trace_attributes to see if they end up correct when i call top k with k=2.

something niave like:

```
                               _________________________
                              /     Street B
                             /                     x
___x_________________x______/
        Street A            \
                             \
                              \_________________________
                                    Street C
```

where `k=0` would be A->B and `k=1` would be A->C

**Comment by ptpt** [comment]
That's even better.

I think the unit test is still necessary but we can add it later.

**Comment by kevinkreiser** [comment]
awesome ill do it right away! agreed we should do both to validate the top k algorithm brute force

**Comment by ptpt** [comment]
Only unit tests are left to do for this PR. I will add them in `test/viterbi_search.cc` because we can use some of the generator functions defined there.

**Comment by kevinkreiser** [comment]
@ptpt im working on the street name test mentioned above right now

**Comment by ptpt** [comment]
Thanks for the PR @kevinkreiser 

I'm trying to get the PR ready tonight. The plan will be:

1. Add the unit tests to make sure `TopKSearch` works
2. Add a new method called `MapMatcher::OfflineMatchTopK` and make sure it works with your tests.

`MapMatcher::OfflineMatchTopK` will replace `MapMatcher::OfflineMatch` in later PRs. Because in `MapMatcher::OfflineMatchTopK` we will introduce some code that `TopKSearch` depends on and also we will remove some code that `OfflineMatch` depends on. It's safer to have a well-tested method first and then replace. WDYT?

**Comment by kevinkreiser** [comment]
That sounds great to me @ptpt let me know when and where i can help

**Comment by ptpt** [comment]
Some changes since yesterday:

1. add topksearch tests (still failing but should be fixed soon)
2. bring back the old `OfflineMatch` (from master branch) as `OfflineMatch1` and use it if k==1

**Comment by ptpt** [comment]
It seems that the TopKSearch algorithm is broken; the path isn't completely removed so we always get same top 1 path even after removing it. I have a fix in mind but need some investigation. Will work on it tonight.

**Comment by ptpt** [comment]
Some changes over the weekend:

1. the topk works now; top k paths it returns match the paths from the brute force one (see the test)

TODO:
1. [ ] fix `OfflineMatch`, which doesn't work with topk yet.

**Comment by ptpt** [comment]
Still failing. If I disable `OfflineMatch1` (the original OfflineMatch), and use topk completely, I got

```
=== Testing map matcher ===
                       test32bit  [PASS]
                    test_matcher  [FAIL: Map Match algorithm failed to find path:map_snap algorithm failed to snap the shape points to the correct shape.No path could be found for input]
              test_distance_only  [FAIL: Map Match algorithm failed to find path:map_snap algorithm failed to snap the shape points to the correct shape.No path could be found for input]
             test_time_rejection  [FAIL: Map Match algorithm failed to find path:map_snap algorithm failed to snap the shape points to the correct shape.No path could be found for input]
                       test_topk  [FAIL: Map Match algorithm failed to find path:map_snap algorithm failed to snap the shape points to the correct shape.No path could be found for input]
=== Failed 4 tests ===
```

It seems that we got unexpected broken paths, and the trace_action would throw an exception 442 if it sees broken paths.

**Comment by kevinkreiser** [comment]
@ptpt i havent had time to look at this recently ill have a look as soon as i can

**Comment by ptpt** [comment]
@kevinkreiser No worries. This is completely related to meili that it can't find the path.

**Comment by ptpt** [comment]
The topk should be fixed. However, `test_topk` still fail. I'm not sure if we should update the test or the implementation.

The best path I get in `test_topk` looks correct. But it consists of 4 edges with names `"Prins Hendriklaan", "Prins Hendriklaan", "Sophocleslaan", "Sophocleslaan"` respectively.


```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.15248,
          52.084202
        ]
      },
      "properties": {
        "marker-color": "#abd9e9",
        "marker-size": "small",
        "trace_point_index": 0
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.15295,
          52.084438
        ]
      },
      "properties": {
        "marker-color": "#abd9e9",
        "marker-size": "small",
        "trace_point_index": 1
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.15345,
          52.084591
        ]
      },
      "properties": {
        "marker-color": "#abd9e9",
        "marker-size": "small",
        "trace_point_index": 2
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.152473,
          52.084206
        ]
      },
      "properties": {
        "marker-color": "#2c7bb6",
        "marker-size": "medium",
        "matched_point_index": 0,
        "matched_point_type": "matched",
        "edge_index": 0,
        "distance_along_edge": 0.557,
        "distance_from_trace_point": 0.643
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.152952,
          52.084438
        ]
      },
      "properties": {
        "marker-color": "#2c7bb6",
        "marker-size": "medium",
        "matched_point_index": 1,
        "matched_point_type": "matched",
        "edge_index": 1,
        "distance_along_edge": 0.586,
        "distance_from_trace_point": 0.13
      }
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          5.15336,
          52.084648
        ]
      },
      "properties": {
        "marker-color": "#2c7bb6",
        "marker-size": "medium",
        "matched_point_index": 2,
        "matched_point_type": "matched",
        "edge_index": 3,
        "distance_along_edge": 0.077,
        "distance_from_trace_point": 8.782
      }
    }
  ]
}
```

The second best path ends at the intersection:


```json
{"type":"FeatureCollection","features":[                                      
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.152480,52.084202]},"properties":{"marker-color":"#abd9e9","marker-size":"small","trace_point_index":0}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.152950,52.084438]},"properties":{"marker-color":"#abd9e9","marker-size":"small","trace_point_index":1}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.153450,52.084591]},"properties":{"marker-color":"#abd9e9","marker-size":"small","trace_point_index":2}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.152473,52.084206]},"properties":{"marker-color":"#2c7bb6","marker-size":"medium","matched_point_index":0,"matched_point_type":"matched","edge_index":0,"distance_along_edge":0.557,"distance_from_trace_point":0.643}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.152952,52.084438]},"properties":{"marker-color":"#2c7bb6","marker-size":"medium","matched_point_index":1,"matched_point_type":"matched","edge_index":1,"distance_along_edge":0.586,"distance_from_trace_point":0.130}},
{"type":"Feature","geometry":{"type":"Point","coordinates":[5.153277,52.084599]},"properties":{"marker-color":"#2c7bb6","marker-size":"medium","matched_point_index":2,"matched_point_type":"matched","edge_index":2,"distance_along_edge":1.000,"distance_from_trace_point":11.791}}
]} 
```

**Comment by ptpt** [comment]
I'm ready to merge this PR if we resolve the tests.

**Comment by kevinkreiser** [comment]
@ptpt sorry been busy with other things ill have a look at this now

**Comment by ptpt** [comment]
Thanks @kevinkreiser merging now.

**Pull request merged**
