### PR TITLE
Fix unaligned reads

### PR DESCRIPTION
**Pull request by oleg-liatte**
# Issue

Read of unaligned structs that require alignment causes performance degradation or even UB on some platforms.

This fix introduces `unaligned_read()` function template to safely access unaligned structs and fixes the issue for `linguistic_text_header_t` struct.

See https://stackoverflow.com/questions/48312068/fast-memcpy-for-small-unaligned-data for more details.

### CODE REVIEW

**Review by kevinkreiser — APPROVED** [review]
I was just also looking into this, thanks for grabbing it!

**Review by dgearhart — APPROVED** [review]
:ship: thank you

**Comment by oleg-liatte** [comment]
@kevinkreiser @dgearhart could you re-approve, as resolving conflict with master (in changelog) dismissed your approvals

**Review by dgearhart — APPROVED** [review]
re-approved

**Pull request merged**
