### PR TITLE
Elevation service

### PR DESCRIPTION
**Pull request by dnesbitt61**
Simple doc describing how to run an elevation lookup service.

### CODE REVIEW

**Comment by chrislukic** [comment]
Thanks for this. I suspect many people will be looking to set up Valhalla servers since there are no real elevation APIs comparable to what Mapzen provided.  

With this in mind, perhaps you could include a brief note about hardware/hosting recommendations in the doc.

For example, is it possible/practical to host on AWS and source the elevation data directly from the S3 public data store, perhaps behind cloudfront? Or if on dedicated hardware, will a 2TB rotational hard drive suffice for the complete elevation datastore, or is an SSD recommended?

**Comment by dnesbitt61** [comment]
We are running a hosted Elevation Service at Mapbox so that is one place to try.
We are running on AWS with Cloudfront at Mapbox. I can't comment on using rotation hard drive vs. SSD - we have always used SSD when testing locally. If you aren't worried about latency of initial responses then rotational drives may be fine.

**Comment by chrislukic** [comment]
Right, I understand the whole team has moved to Mapbox.  I would love to move as well. Unfortunately, I can't find any docs on an equivalent product. 
https://www.mapbox.com/api-documentation makes no reference to elevation. And the surface API docs from 2014 don't align with what Valhalla provides.

With regards to self hosting, if I install Valhalla on AWS, then it's not clear to me from the docs how I configure it to point to the public S3 tileset. In this scenario, the bash script to retrieve the 1.6TB of elevation data would not be required correct? and I could instead somehow point Valhalla to a Cloudfront distribution in front of the public S3 dataset?

(thanks for taking the time to respond, and please forgive my obvious inexpertise)

**Comment by kevinkreiser** [comment]
@chrislukic The documentation for the service is the same as ever and can be found in the [valhalla-docs repo](https://github.com/valhalla/valhalla-docs/tree/master/elevation). Right now I think you might do best to reach out to the sales team at Mapbox to start using the service while we are in this transitional phase.

**Comment by chrislukic** [comment]
Thanks for the response. I've taken your advice and reached out to Mapbox sales and am awaiting a response.

I take it that Valhalla can not point directly to s3:/elevation-tiles-prod/skadi/ but instead must build a local elevation tileset using scripts/valhalla_build_elevation. I saw some mention that of support for lz4 compression. In that case, how would someone configure the script to use this compression and what would be the total compressed size required?

**Comment by kevinkreiser** [comment]
right so you cant configure it to use the s3 bucket directly (although this would be pretty easy to add). the point of the compression is so that moving the data to a server doesnt take eons. the world wide uncompressed set costs about 1.6TB so its gzipped in the s3 bucket and is about 190GB. the code can work with compressed sources that are on local disk but gzip is super slow to decompress on the fly and lz4, while faster, isnt good enough for running a real server with a widely varying set of requests

**Pull request merged**
