### PR TITLE
french translation correction

### PR DESCRIPTION
**Pull request by xlqian**
# Issue

just a new corrections in french translation

## Tasklist

 - [ ] Update the [changelog](CHANGELOG.md)

### CODE REVIEW

**Comment by SGrenet** [comment]
add https://navitia.atlassian.net/browse/NAV-2032 in description please

**Comment by nilsnolde** [comment]
Can we keep these things on transifex? The only thing being pushed _to_ transifex from this repo should be the master JSON (i.e. english). Sorry for the push-back, it just removes a few headaches if we keep it consistent.

**Comment by xlqian** [comment]
hi,  no problem. but can you be more specific about what I'm supposed to do, please?

**Comment by xlqian** [comment]
I just found the guideline, never mind :)

**Comment by xlqian** [comment]
hi, I just uploaded a JSON for fr with corrected translations, what am I supposed to do now?

**Comment by nilsnolde** [comment]
Cool, thanks. Now a transifex admin has to pull it and check it into the Valhalla repo. We usually do that before releases (if we remember). Is that ok? Or are you keeping up with master and want to have it now? 

FWIW, you can check that JSON into your fork, next release it'll cleanly merge with an updated upstream master. I just don't like that workflow for this repo, rather keep all in one place, i.e. transifex.

**Comment by kevinkreiser** [comment]
i dont think we have to wait for releases. ive not pulled it using the tooling transifex but unless its horrible its ok to do updates by request. i mean thats what we did last time. someone asked for it so we said sure.

**Comment by nilsnolde** [comment]
done

**Pull request closed without merging**
