### PR TITLE
Remove simple restriction check for pedestrians

### LINKED ISSUE #3403: Restriction relations without foot type applied for pedestrian routing
Hi,
It seems that restrictions without foot type specified are also applied tor pedestrian routing. However according to https://wiki.openstreetmap.org/w/index.php?title=Relation:restriction, point "Turn restrictions do not apply to pedestrian unless the type or key is restriction:foot", this shouldn't be done. Any comments on this? Is this a bug or feature?

I assume this is related to OSM tags processing in Lua, https://github.com/valhalla/valhalla/blob/8921a1d22368e3198dd157a9587447cacfefcd00/lua/graph.lua#L2129.

### PR DESCRIPTION
**Pull request by szymone**
# Issue

Fixes #3403

### CODE REVIEW

**Comment by kevinkreiser** [comment]
Would you mind adding a quick gurka test for this. We would be happy to show you how and it will prevent regressions in the future

**Comment by szymone** [comment]
@kevinkreiser Sure. Can you share some more information how to do this or provide some example?

**Comment by kevinkreiser** [comment]
@szymone yep actually you are in luck, we just had another similar PR where i asked the contributor to do just about the same thing (but for buses), let me know if this comment sheds any light: https://github.com/valhalla/valhalla/pull/3413#issuecomment-974514177

**Comment by szymone** [comment]
@kevinkreiser I've added one test for this. Can you look at it?

**Comment by szymone** [comment]
@kevinkreiser Any update on this? Is this test enough to merge this PR?

**Review by kevinkreiser — APPROVED** [review]

**Comment by kevinkreiser** [comment]
sorry for the delay on that im currently trying to take some days off while also fighting a pretty strong cold

**Pull request merged**
