### PR TITLE
fix dow and exception when after midnight trips are normalised

### LINKED ISSUE #1681: Transit: after midnight dow and exception date are wrong

### PR DESCRIPTION
**Pull request by slvlirnoff**
# Issue

fixes #1681
Sorry I don't have a lot of time to check syntax and the logic. It is adapted from a patch we use in our system.

## Tasklist

 - [ ] Add tests
 - [ ] Review - you must request approval to merge any PR to master
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Generally use squash merge to rebase and clean comments before merging
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by gknisely** [comment]
@slvlirnoff `ci/circleci: lint` is failing due to not running `./scripts/format.sh`  Can you run this and check in your updates?

**Comment by slvlirnoff** [comment]
@gknisely done, thanks

**Comment by gknisely** [comment]
@drewda @irees This looks good to me, but can you try it out by any chance?  I hope all is well.

**Comment by drewda** [comment]
hi @gknisely, happy new year! @ian is going to test and report back.

**Comment by irees** [comment]
@gknisely I read through the issue and pr and this looks fine to me. I will make a corresponding change in Transitland's own tile export functionality.

**Comment by gknisely** [comment]
@slvlirnoff @drewda @irees Thank you

**Pull request merged**
