### PR TITLE
Add driving_side for OSRM serialization 

### LINKED ISSUE #1672: Set correct driving side with OSRM serialization
This was left as a TODO in code. use the setting in the Trippath to set this value to right or left.

### PR DESCRIPTION
**Pull request by dnesbitt61**
(was a TODO and always set to right).

fixes #1672 

 - [ ] Add tests
 - [x] Review - you must request approval to merge any PR to master
 - [ ] Add #fixes with the issue number that this PR addresses
 - [x] Generally use squash merge to rebase and clean comments before merging
 - [x] Update the [changelog](CHANGELOG.md)
 - [ ] Update relevant [documentation](docs/README.md)

### CODE REVIEW

**Comment by brentnd** [comment]
What's the general process for propagating this change to the downstream mapbox offline navigation engine?

**Comment by kevinkreiser** [comment]
@brentnd
we merge this to master :heavy_check_mark: 
we cut a release of the offline navigation engine :white_check_mark:

**Comment by brentnd** [comment]
@kevinkreiser awesome.

**Comment by JFDionne** [comment]
Hi, it's seem it return always "left" for me, right now, It's there a configuration somewhere?

**Comment by kevinkreiser** [comment]
@JFDionne the driving side is set in the data when we build the tiles. It uses admin information to do so. You need to run `valhalla_build_admins` first and then build tiles using that admins information when building tiles.

**Comment by JFDionne** [comment]
Thank, I'll check that,

**Pull request merged**
