### PR TITLE
Clean up meili

### PR DESCRIPTION
**Pull request by ptpt**
This PR

1. remove `MapMatching`
2. use `TransitionCostModel` and `EmissionCostModel`
3. Add `StateContainer` that manages measurements and candidates. It also maps stateids and states

### CODE REVIEW

**Comment by kevinkreiser** [comment]
this looks fine to me but it seems somehow to have affected the way that `traffic_segment_matcher.cc` is making use of the matching. any chance you could have a look over that code to make sure its using it in the way that it should be wrt these changes?

**Comment by ptpt** [comment]
Noticed "segmentation fault" when calling `OfflineMatch` multiple times. Investigating...

**Comment by ptpt** [comment]
"segmentation fault" is thrown in the master branch too.

**Comment by ptpt** [comment]
"segmentation fault" was fixed in https://github.com/valhalla/valhalla/pull/940

**Pull request merged**
