### PR TITLE
fix CHANGELOG release year (2022->2023)

### PR DESCRIPTION
**Pull request by ImreSamu**
# Issue

fix CHANGELOG release year (2022->2023)

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [X] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations
Link any requirements here. Other pull requests this PR is based on?

- No

### CODE REVIEW

**Review by nilsnolde — APPROVED** [review]
Thanks for the cleanup! I guess for me, it’s cool without an actual entry in the changelog to reduce noise, but don’t really care either :)

**Review by kevinkreiser — APPROVED** [review]

**Comment by kevinkreiser** [comment]
agree the entry was not needed but I didn't want to wait to get it removed so I just forced it through

**Comment by ImreSamu** [comment]
@kevinkreiser :
Is it possible to correct the years here? --->  https://github.com/valhalla/valhalla/releases

**Comment by kevinkreiser** [comment]
done

**Pull request merged**
