### PR TITLE
Edgestatus Revisions

### PR DESCRIPTION
**Pull request by dnesbitt61**
The basic change is to replace the unordered map with edge Ids as the key with an unordered_map with the tile Id as the key and an allocated array of EdgeStatusInfo as the value. Add a method to return a pointer to an EdgeStatusInfo that can be incremented for sequential edges - thus saving many lookups in the hash map. Some performance tests indicate pathfinding for long routes is improved with some route computations taking half as long as before (example - long bicycle route went from 1960ms down to 950ms). Testing Lancaster PA to San Diego CA automobile route improved from 350ms to 210ms.

fixes https://github.com/valhalla/valhalla/issues/250

In addition to noting that EdgeStatus was sometimes taking a long time to clear after long routes it was also seen that performance changed dramatically with different reserve and load_factor settings for the unordered_map that associated the edge Ids with EdgeStatusInfo.  Trying boost unordered_map did not improve the situation. 

Further testing is needed, but Bidirectional A* yields consistent results when compared with prior code. Making sure memory use is not increased (it should be decreased but need to verify) and testing of multimodal and isochrones is needed.

### CODE REVIEW

**Comment by dnesbitt61** [comment]
Some performance and memory use tests have indicated that memory use is slightly less on routes of different lengths. Performance improvement is most on long routes but even short routes show some improvement (e.g. New York to Philadelphia improved from 32ms to 24ms).

**Comment by dnesbitt61** [comment]
multimodal checks out so I think this is ready for wider integration testing.

**Comment by dgearhart** [comment]
**de_benchmark_notes_20180404_master**

```
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 1 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 1 concurrent users for battle.
The server is now under siege..      done.

Transactions:		        2550 hits
Availability:		      100.00 %
Elapsed time:		       86.07 secs
Data transferred:	       57.03 MB
Response time:		        0.03 secs
Transaction rate:	       29.63 trans/sec
Throughput:		        0.66 MB/sec
Concurrency:		        1.00
Successful transactions:        2550
Failed transactions:	           0
Longest transaction:	        0.13
Shortest transaction:	        0.00
 
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 2 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 2 concurrent users for battle.
The server is now under siege..      done.

Transactions:		        5100 hits
Availability:		      100.00 %
Elapsed time:		      117.98 secs
Data transferred:	      114.07 MB
Response time:		        0.05 secs
Transaction rate:	       43.23 trans/sec
Throughput:		        0.97 MB/sec
Concurrency:		        2.00
Successful transactions:        5100
Failed transactions:	           0
Longest transaction:	        0.19
Shortest transaction:	        0.00
 
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 4 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 4 concurrent users for battle.
The server is now under siege..      done.

Transactions:		       10200 hits
Availability:		      100.00 %
Elapsed time:		      196.88 secs
Data transferred:	      228.13 MB
Response time:		        0.08 secs
Transaction rate:	       51.81 trans/sec
Throughput:		        1.16 MB/sec
Concurrency:		        3.97
Successful transactions:       10200
Failed transactions:	           0
Longest transaction:	        0.32
Shortest transaction:	        0.01
 ```

**Comment by dgearhart** [comment]
**de_benchmark_notes_20180404_edgestatus**
```
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 1 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 1 concurrent users for battle.
The server is now under siege..      done.

Transactions:		        2550 hits
Availability:		      100.00 %
Elapsed time:		       56.75 secs
Data transferred:	       57.03 MB
Response time:		        0.02 secs
Transaction rate:	       44.93 trans/sec
Throughput:		        1.00 MB/sec
Concurrency:		        1.00
Successful transactions:        2550
Failed transactions:	           0
Longest transaction:	        0.07
Shortest transaction:	        0.00
 
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 2 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 2 concurrent users for battle.
The server is now under siege..      done.

Transactions:		        5100 hits
Availability:		      100.00 %
Elapsed time:		       77.82 secs
Data transferred:	      114.07 MB
Response time:		        0.03 secs
Transaction rate:	       65.54 trans/sec
Throughput:		        1.47 MB/sec
Concurrency:		        2.00
Successful transactions:        5100
Failed transactions:	           0
Longest transaction:	        0.12
Shortest transaction:	        0.00
 
dgearhart@dgearhart:/data/OLD/perf_test$ siege -c 4 -b -r 2550 -f url_de_benchmark_routes.txt
** SIEGE 3.0.8
** Preparing 4 concurrent users for battle.
The server is now under siege..      done.

Transactions:		       10200 hits
Availability:		      100.00 %
Elapsed time:		      122.92 secs
Data transferred:	      228.13 MB
Response time:		        0.05 secs
Transaction rate:	       82.98 trans/sec
Throughput:		        1.86 MB/sec
Concurrency:		        4.00
Successful transactions:       10200
Failed transactions:	           0
Longest transaction:	        0.18
Shortest transaction:	        0.00
```

**Comment by kevinkreiser** [comment]
60% performance increase!?!?!?! @dnesbit61 you deserve a chicken dinner, maybe 2!

**Pull request merged**
