### PR TITLE
towards fixing disconnected islands

### LINKED ISSUE #72: Locate more results
(2016-11-16T22:26:41Z) @kevinkreiser : originally created valhalla/loki#164

We should allow locate to configure results based on radius or number of results. This should allow for clients to survey the area near their locations and use those results to give hints to routing about which locations they would prefer.

so for example someone might drop a pin, get back 10 streets nearby, the client then does some matching of the street name information and uses the way_id of that matching edge for the route.

cc: @smWork @noblige @yzadik

(2016-11-21T19:47:57Z) @kevinkreiser : it might be nice to get the way_id favoring in for this as well. its not necessary because you'll have the exact correlation point but it would be a nice easy addition to do simultaneously.

### PR DESCRIPTION
**Pull request by kevinkreiser**
## what are islands

disconnected islands have been a long standing problem in valhalla. there are many cases for which the starting conditions of the route lead to a bad (or no) result in the end. essentially before we do the route computation we need to initialize some state. this state describes, among other things, where the given route will start and end in terms of which edges in the graph those locations best match. the problem here is that figuring out the best match is non trivial. so we started off with a simple idea of just taking the closest usable graph edge for a given location. the problem was that if this edge was on a disconnected island and the other edge was not on that same island, the route would fail. 

noroute

great then just make sure not to  use any disconnected island candidates. this has the problem that then we'd get a route but it could be sub optimal. say you are routing on a campus thats disconnected. do you really want the route to take place outside of the campus when it could have been completed inside the campus?

nonislandonly

there's another issue as well with dead ends. sometimes the best result is a dead end. a oneway into a parking lot, that for example, you are trying to leave. you might say well this is clearly bad data, but even this isnt the case. maybe you parked near where you came into the parking lot so the candidate nearest you can only enter the parking lot but there is a one way out of the parking lot further away from you.

cantleave

in any case the issues are multiple and non trivial.

## how did we fix (most of) them

we needed to tackle two problems. the first problem was that we needed to be able to return more than one candidate for a given location. you can see from the examples where you have a small disconnected island, if you had another less likely candidate in the connected region (not an island) you'd have completed the route. so the first step was allowing the algorithm to give back more than one candidate and assign weights (penalties) to them accordingly. the second problem was that we needed to get an approximation of whether a given edge (candidate) was part of a small disconnected island or a larger connected one. this would allow us to keep searching for more candidates until we satisfied the requirement of at least one candidate who meets the connectivity requirement (or exhaust the distance limit).

### radius threshold

to solve the first of the two problems we've added an optional `radius` to each input location. with this you can specify in meters a radius about the input to return candidates from. if there are no candidates within this radius you'll still get the closest result within reason (some small number of km from the input).

### reachability threshold

to solve the second problem we categorize each candidate as reachable or unreachable based on an optional `minimum_reachability` parameter also on each input location. with this you can specify the minimum number of graph nodes that are reachable from a given graph node to qualify it as a connected region. have a read of wikipedia for more info on [reachability in graph theory](https://en.wikipedia.org/wiki/Reachability). the important thing here is that we compute reachability on the fly. this has implications on performance. we could indeed store reachability per node (using the spare bits in the `directededge`s `end_node` field) but the dynamic nature of our costing models would make this quite tricky. basically if you precomputed reachability you'd need to do it for all modes of travel, adding a new one would mean having to make new data and so on. you could precompute an upper bound but you'd still need to do a computation on the fly to make sure the real reachability for a given node wasnt less for the mode of travel in the request. in the end we decided to just do the whole thing on the fly.

## performance

valhalla comes with a benchmark of this location candidate searching functionality. previously @TeXitoi and @xlqian did a bunch of work to speed up this part of valhalla. solving this problem was indeed going to cost some cpu cycles for sure. heres a comparision of before these changes, after these changes but not using radius or reachability and then after these changes but using a radius of 50 and a reachability of 50. we show both single location search as well as batches of 200 on a test dataset for the eastern US.

|      | batch | radius | reachability | ms per location |
| :--- |  ---: |   ---: |         ---: |            ---: |
| **old code** | 1 | n/a | n/a | 0.097 |
| **new code** | 1 | 0 | 0 | 0.092 |
| **new code** | 1 | 50 | 50 | 0.264 |
| **old code** | 200 | n/a | n/a | 0.062 |
| **new code** | 200 | 0 | 0 | 0.063 |
| **new code** | 200 | 50 | 50 | 0.071 |

there are a couple things of note here. first is that disabling radius and reachability make the code take about the same (sometimes less) time than the old code. technically the code is doing more work but i found a few more efficiency gains in the point projection code that was optimized by the navitia folks above to mitigate this. adding radius and reachability into the mix you'll notice that only the non batch case suffers a slowdown. this is almost all due to cache coherency with the reachability computation; the radius has little to no impact for small (ie. reasonable) radius sizes. see the reachability shares information accross locations, so if locations are close within the batch they can reuse reachability information thats already been computed for other locations. to put it another way, the reason the batch case does not suffer too much slowdown is because it can take advantage of using the reachability cache for more than one location instead of computing this cache for each location in isolation. also its good to note that in practice we always use a batch size of at least 2 locations (when routing) so this is somewhat comforting. also the fact that its still only a quarter of a millisecond per location seems negligable although still measurable.

## future work

because of the naive way we measure reachability, we over estimate the reachability of certain graph nodes in the presence of one ways. this can be handled if we track both the forward and backward reachability of a given node and i have some ideas to accomplish by revamp the way we compute reachability. essentially we dont handle the case above where you cant leave the parking lot because we only measure reachability in whatever direction is permitted. fixing this this felt outside the scope of this PR and seemed like a good improvement to build on what has been done here so i'll save it for a little later.

@noblige fixes #72 #58

### CODE REVIEW

**Comment by dnesbitt61** [comment]
:shipit:

**Comment by dgearhart** [comment]
@kevinkreiser nice write up
Did you say that these routes now work properly?
https://github.com/valhalla/valhalla/blob/master/test_requests/pl_pedestrian_routes.txt

**Comment by kevinkreiser** [comment]
@dgearhart yep if you add `"minimum_reachability":50` on the origin of those then they find a path

**Comment by dgearhart** [comment]
:shipit:

**Comment by kevinkreiser** [comment]
so i've done some more adhoc testing of this based on the polish routes @dgearhart linked and found that users could concoct some routes that give rather odd results. note that it may not be worth spending time on right now as the use case is highly contrived and will be alleviated by sane defaults in the service.

unfortunate
http://valhalla.github.io/demos/routing/index-internal.html#loc=17,54.262213,18.631579&locations=[{%22lat%22:54.26178,%22lon%22:18.63581,%22minimum_reachability%22:50},{%22lat%22:54.26287,%22lon%22:18.62818}]&costing=%22pedestrian%22&directionsoptions={%22language%22:%22en-US%22}

basically you find a disconnected island. find a connected region near by. put the destination in the disconnected island but only enable reachability on the origin and set a radius of 0. a radius of zero means you must take the closest result so long as its reachable. this causes the destination to assume every candidate is reachable and so it only finds one candidate. the one in the disconnected island. meanwhile the origin is in the same bin as the destination, so it sees all the same edges. it classifies its closest reachable one as in the connected region but it also sees the edges in the disconnected island and classifies those as the closest not reachable ones.

since the destination only has one edge thats in the disconnected island the only path can be the one where the origin is also in the disconnected island.

so yeah this problem is basically garbage in garbage out, the request has unreasonable constraints. just wanted to note that.

**Comment by kevinkreiser** [comment]
i was writing this before when looking at that poland issue above but yeah this can lead to senarios where the trivial path logic fires because locations are close enough together that they both find the same  unreachable islands and that route is faster than the real route.

**Pull request merged**
