### PR TITLE
Set service road use in GetTripLegUse.

### PR DESCRIPTION
**Pull request by dnesbitt61**
# Issue

Service road use was missing from the case statement in proto conversion GetTripLegUse method. This fixes that omission.

## Tasklist

 - [ ] Add tests
 - [ ] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [ ] Update the [changelog](CHANGELOG.md)
 - [ ] If you made changes to the lua files, update the [taginfo](taginfo.json) too.

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Review by gknisely — DISMISSED** [review]

**Comment by kevinkreiser** [comment]
@dnesbitt61 this seems to be causing the release build to fail! the change looks simple enough but for whatever reason the release build is saying stuff like:

```
Expected: gurka::do_action(valhalla::Options::route, ignore_access_map, {"A", "B", "D"}, cost, {{IgnoreAccessParam(cost), "1"}}) doesn't throw an exception.
  Actual: it throws valhalla::valhalla_exception_t with description "Could not build directions for TripLeg".
```

which looks directly related to me!

**Comment by dnesbitt61** [comment]
ughh...will look in the next day or 2

**Comment by dnesbitt61** [comment]
looks like EnhancedTipPath needed a mapping for kServiceRoadUse.

**Comment by gknisely** [comment]
> looks like EnhancedTipPath needed a mapping for kServiceRoadUse.

@dnesbitt61 I am waiting for my :beer:  ;-)

**Review by gknisely — APPROVED** [review]

**Pull request merged**
