### PR TITLE
Fixed incorrect routing through `motor_vehicle:conditional=destination`.

### PR DESCRIPTION
**Pull request by maksimandrianov**
I need create a new PR after `git push force`.
Old PR https://github.com/valhalla/valhalla/pull/3041

# Issue

Valhalla incorrect works when acts restriction by time limit for vehicles (period specified in the tag):

build route to roads which can only be visited by driving through the such roads (road with tag `motor_vehicle:conditional`=destination + other road = the only way)
on whole distance of road with tag `motor_vehicle:conditional`=destination. Works only on some parts of such roads.
When restriction by time limit doesn't act - routing correct.

What did you expect to happen?
This restriction (in the specified time period) should to avoid such roads from transit routing, but as destination and the only way they should be suggest.

## Tasklist

 - [x] Add tests
 - [x] Add #fixes with the issue number that this PR addresses
 - [ ] Update the docs with any new request parameters or changes to behavior described
 - [x] Update the [changelog](CHANGELOG.md)

## Requirements / Relations

 Link any requirements here. Other pull requests this PR is based on?

### CODE REVIEW

**Comment by gknisely** [comment]
@maksimandrianov why did you open a new PR?  Now folks don't even know where we left off with the updates that were requested.  I am now unsure of the state of this PR and concerned.

**Comment by SvetlanaBayarovich** [comment]
@gknisely To my knowledge the old pr got messed up after force push and shows zero diff now 😞 Is there any chance at all to restore it somehow?

**Comment by maksimandrianov** [comment]
> @maksimandrianov why did you open a new PR? Now folks don't even know where we left off with the updates that were requested. I am now unsure of the state of this PR and concerned.

The old PR was closed automatically after `git push force`. I cannot restore the old PR, because my changes were disappeared in the old PR #3041. . :(

**Review by genadz — DISMISSED** [review]

**Comment by mandeepsandhu** [comment]
> > @maksimandrianov why did you open a new PR? Now folks don't even know where we left off with the updates that were requested. I am now unsure of the state of this PR and concerned.
> 
> The old PR was closed automatically after `git push force`. I cannot restore the old PR, because my changes were disappeared in the old PR #3041. . :(

Thats odd. I do `git push -f origin <branch name>` quite often, but haven't had my diffs disappear. What was the exact command you gave?

**Comment by maksimandrianov** [comment]
> > > @maksimandrianov why did you open a new PR? Now folks don't even know where we left off with the updates that were requested. I am now unsure of the state of this PR and concerned.
> > 
> > 
> > The old PR was closed automatically after `git push force`. I cannot restore the old PR, because my changes were disappeared in the old PR #3041. . :(
> 
> Thats odd. I do `git push -f origin <branch name>` quite often, but haven't had my diffs disappear. What was the exact command you gave?

I had used many commands before I noticed that diffs disappeared and PR was closed. I agree, thats odd. There is the same compare branch `routing_through_conditional_destination_fix` for this PR and the old PR, but there are no diffs for the old PR:(

**Comment by gknisely** [comment]
@maksimandrianov this looks good but did you do a round of RAD/QT testing.  We usually test with 

```
turn_lane_routes.txt
turn_type_routes.txt
demo_routes.txt
roundabout_routes.txt
bicycle_routes.txt
pedestrian_routes.txt
ferry_routes.txt
turn_channel_routes.txt
jughandle_routes.txt
ramp_routes.txt
ramp_fork_routes.txt
timed_conditional_routes.txt
pa_interchange_routes.txt
md_interchange_routes.txt
oh_interchange_routes.txt
highway_cardinal_direction_routes.txt
bear_vs_straight_routes.txt
pedestrian_roundabout_routes.txt
internal_edge_routes.txt
es_routes.txt
eu_motorroad.txt
euro_bicycle_routes.txt
li_routes.txt
nl_bicycle_routes.txt
pl_pedestrian_routes.txt
si_roundabout_routes.txt
uk_routes.txt
de_benchmark_routes.txt

And our internal 1k production file.
```

**Comment by maksimandrianov** [comment]
> @maksimandrianov this looks good but did you do a round of RAD/QT testing. We usually test with
> 
> ```
> turn_lane_routes.txt
> turn_type_routes.txt
> demo_routes.txt
> roundabout_routes.txt
> bicycle_routes.txt
> pedestrian_routes.txt
> ferry_routes.txt
> turn_channel_routes.txt
> jughandle_routes.txt
> ramp_routes.txt
> ramp_fork_routes.txt
> timed_conditional_routes.txt
> pa_interchange_routes.txt
> md_interchange_routes.txt
> oh_interchange_routes.txt
> highway_cardinal_direction_routes.txt
> bear_vs_straight_routes.txt
> pedestrian_roundabout_routes.txt
> internal_edge_routes.txt
> es_routes.txt
> eu_motorroad.txt
> euro_bicycle_routes.txt
> li_routes.txt
> nl_bicycle_routes.txt
> pl_pedestrian_routes.txt
> si_roundabout_routes.txt
> uk_routes.txt
> de_benchmark_routes.txt
> 
> And our internal 1k production file.
> ```
> 
> Hopefully, there are no bad routes created.

It was tested and there are no bad routes. I send you a private message with the link on the results.

**Review by gknisely — APPROVED** [review]

**Pull request merged**
