### PR TITLE
Add CMakeSettings.json with reasonable defaults [ci skip]

### PR DESCRIPTION
**Pull request by mloskot**
`CMakeSettings.json` is convenient to control build configuration when using [CMake integration with Visual Studio 2017](https://go.microsoft.com//fwlink//?linkid=834763).

Usage:
 - Copy cmake/CMakeSettings.json to top-level directory of  Valhalla source tree
 - In VS2017 > File > Open > CMake > select top-level CMakeLists.txt
 - Edit CMakeSettings.json, flip options, add options for dependencies, etc.

Ignore user-speciifc local directory managed by CLion IDE.

### CODE REVIEW

**Comment by mloskot** [comment]
Thanks for accepting it

**Comment by alecava58** [comment]
Hi all,

I'm trying to build on windows but cmake returns the following error:

Studio/2017/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)		

How can download the required library?

**Comment by mloskot** [comment]
@alecava58 Valhalla does not ship any dependencies in binary form. You need to download, build and deploy those yourself. It means, you choose your preferred way to install the required libraries in your development environment on Windows (e.g. download and build source packages manually or use a package manager like Conan or Vcpkg or whatever you are familiar with).

A reasonable bet is to learn what AppVeyor configuration for Valhalla does in order to build on Windows with VS2017. If you read https://github.com/valhalla/valhalla/blob/master/.appveyor.yml, among other steps, you will see this:

https://github.com/valhalla/valhalla/blob/ab6e86ab6691f0175a101f827be98658c567c8b2/.appveyor.yml#L52-L54

**Comment by alecava58** [comment]
thanks a lot @mloskot for the detailed answer.

**Pull request merged**
